name: sls
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - pytorch=1.7.1
  - torchvision=0.8.2
  - cudatoolkit=11.0
  - numpy=1.19.4
  - tqdm=4.55.1
  - pip
  - pip:
    - imageio==2.9.0
    - matplotlib
    - numba==0.52.0