model:
  arch: "LRN"
  max_channels: 256
  activation: ("LeakyReLU", [0.2, True] )
  upsample: "bilinear"
  use_crp: True
  criterion: (("LogDepthL1Loss",  0.1), )
  predict_log_depth: True


  backbone:
    arch: "efficientnet-b4"
    imagenet: True
    multi_scale_output: True

train:
  batch_size: 16
  lr: 0.0001
  depth_mean: 0.9
  depth_std: 0.3
  
test:
  batch_size: 8
