prefix big_stripes/
prefix big_stripes/position_0.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_0.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_1.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_1.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_2.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_2.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_3.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_3.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_4.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_4.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_5.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_5.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_6.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_6.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_7.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_7.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_8.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_8.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_9.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_9.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_10.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_10.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_11.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_11.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_12.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_12.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_13.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_13.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_14.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_14.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_15.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_15.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_16.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_16.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_17.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_17.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_18.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_18.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_19.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_19.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_20.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_20.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_21.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_21.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_22.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_22.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_23.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_23.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_24.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_24.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_25.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_25.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_26.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_26.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_27.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_27.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_28.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_28.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_29.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_29.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_30.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_30.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_31.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_31.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_32.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_32.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_33.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_33.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_34.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_34.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_35.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_35.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_36.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_36.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_37.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_37.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_38.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_38.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_39.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_39.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_40.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_40.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_41.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_41.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_42.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_42.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_43.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_43.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_44.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_44.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_45.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_45.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_46.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_46.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_47.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_47.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_48.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_48.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_49.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_49.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_50.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_50.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_51.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_51.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_52.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_52.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_53.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_53.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_54.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_54.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_55.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_55.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_56.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_56.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_57.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_57.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_58.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_58.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_59.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_59.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_60.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_60.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_61.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_61.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_62.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_62.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_63.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_63.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_64.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_64.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_65.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_65.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_66.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_66.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_67.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_67.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_68.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_68.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_69.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_69.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_70.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_70.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_71.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_71.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_72.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_72.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_73.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_73.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_74.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_74.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_75.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_75.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_76.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_76.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_77.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_77.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_78.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_78.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_79.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_79.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_80.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_80.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_81.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_81.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_82.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_82.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_83.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_83.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_84.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_84.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_85.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_85.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_86.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_86.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_87.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_87.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_88.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_88.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_89.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_89.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_90.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_90.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_91.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_91.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_92.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_92.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_93.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_93.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_94.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_94.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_95.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_95.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_96.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_96.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_97.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_97.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_98.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_98.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_99.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_99.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_100.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_100.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_101.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_101.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_102.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_102.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_103.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_103.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_104.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_104.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_105.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_105.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_106.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_106.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_107.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_107.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_108.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_108.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_109.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_109.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_110.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_110.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_111.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_111.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_112.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_112.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_113.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_113.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_114.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_114.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_115.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_115.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_116.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_116.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_117.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_117.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_118.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_118.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_119.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_119.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_120.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_120.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_121.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_121.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_122.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_122.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_123.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_123.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_124.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_124.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_125.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_125.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_126.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_126.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_127.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_127.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_128.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_128.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_129.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_129.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_130.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_130.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_131.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_131.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_132.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_132.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_133.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_133.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_134.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_134.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_135.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_135.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_136.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_136.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_137.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_137.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_138.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_138.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_139.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_139.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_140.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_140.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_141.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_141.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_142.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_142.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_143.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_143.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_144.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_144.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_145.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_145.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_146.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_146.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_147.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_147.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_148.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_148.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_149.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_149.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_150.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_150.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_151.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_151.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_152.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_152.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_153.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_153.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_154.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_154.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_155.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_155.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_156.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_156.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_157.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_157.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_158.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_158.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_159.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_159.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_160.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_160.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_161.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_161.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_162.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_162.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_163.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_163.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_164.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_164.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_165.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_165.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_166.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_166.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_167.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_167.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_168.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_168.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_169.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_169.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_170.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_170.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_171.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_171.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_172.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_172.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_173.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_173.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_174.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_174.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_175.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_175.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_176.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_176.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_177.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_177.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_178.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_178.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_179.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_179.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_180.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_180.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_181.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_181.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_182.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_182.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_183.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_183.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_184.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_184.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_185.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_185.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_186.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_186.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_187.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_187.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_188.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_188.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_189.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_189.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_190.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_190.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_191.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_191.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_192.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_192.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_193.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_193.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_194.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_194.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_195.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_195.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_196.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_196.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_197.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_197.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_198.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_198.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_199.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_199.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_200.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_200.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_201.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_201.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_202.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_202.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_203.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_203.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_204.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_204.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_205.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_205.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_206.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_206.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_207.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_207.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_208.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_208.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_209.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_209.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_210.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_210.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_211.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_211.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_212.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_212.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_213.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_213.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_214.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_214.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_215.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_215.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_216.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_216.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_217.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_217.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_218.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_218.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_219.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_219.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_220.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_220.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_221.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_221.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_222.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_222.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_223.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_223.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_224.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_224.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_225.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_225.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_226.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_226.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_227.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_227.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_228.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_228.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_229.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_229.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_230.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_230.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_231.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_231.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_232.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_232.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_233.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_233.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_234.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_234.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_235.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_235.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_236.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_236.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_237.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_237.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_238.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_238.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_239.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_239.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_240.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_240.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_241.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_241.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_242.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_242.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_243.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_243.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_244.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_244.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_245.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_245.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_246.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_246.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_247.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_247.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_248.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_248.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_249.00/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_249.50/
subscript gradient
status
move 0.50
delay 2.000
prefix big_stripes/position_250.00/
subscript gradient
status
