prefix big_stripes/
prefix big_stripes/position_0.00/
subscript gradient
process big_stripes/position_0.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_0.40/
subscript gradient
process big_stripes/position_0.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_0.80/
subscript gradient
process big_stripes/position_0.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_1.20/
subscript gradient
process big_stripes/position_1.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_1.60/
subscript gradient
process big_stripes/position_1.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_2.00/
subscript gradient
process big_stripes/position_2.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_2.40/
subscript gradient
process big_stripes/position_2.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_2.80/
subscript gradient
process big_stripes/position_2.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_3.20/
subscript gradient
process big_stripes/position_3.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_3.60/
subscript gradient
process big_stripes/position_3.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_4.00/
subscript gradient
process big_stripes/position_4.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_4.40/
subscript gradient
process big_stripes/position_4.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_4.80/
subscript gradient
process big_stripes/position_4.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_5.20/
subscript gradient
process big_stripes/position_5.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_5.60/
subscript gradient
process big_stripes/position_5.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_6.00/
subscript gradient
process big_stripes/position_6.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_6.40/
subscript gradient
process big_stripes/position_6.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_6.80/
subscript gradient
process big_stripes/position_6.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_7.20/
subscript gradient
process big_stripes/position_7.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_7.60/
subscript gradient
process big_stripes/position_7.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_8.00/
subscript gradient
process big_stripes/position_8.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_8.40/
subscript gradient
process big_stripes/position_8.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_8.80/
subscript gradient
process big_stripes/position_8.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_9.20/
subscript gradient
process big_stripes/position_9.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_9.60/
subscript gradient
process big_stripes/position_9.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_10.00/
subscript gradient
process big_stripes/position_10.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_10.40/
subscript gradient
process big_stripes/position_10.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_10.80/
subscript gradient
process big_stripes/position_10.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_11.20/
subscript gradient
process big_stripes/position_11.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_11.60/
subscript gradient
process big_stripes/position_11.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_12.00/
subscript gradient
process big_stripes/position_12.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_12.40/
subscript gradient
process big_stripes/position_12.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_12.80/
subscript gradient
process big_stripes/position_12.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_13.20/
subscript gradient
process big_stripes/position_13.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_13.60/
subscript gradient
process big_stripes/position_13.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_14.00/
subscript gradient
process big_stripes/position_14.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_14.40/
subscript gradient
process big_stripes/position_14.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_14.80/
subscript gradient
process big_stripes/position_14.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_15.20/
subscript gradient
process big_stripes/position_15.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_15.60/
subscript gradient
process big_stripes/position_15.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_16.00/
subscript gradient
process big_stripes/position_16.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_16.40/
subscript gradient
process big_stripes/position_16.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_16.80/
subscript gradient
process big_stripes/position_16.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_17.20/
subscript gradient
process big_stripes/position_17.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_17.60/
subscript gradient
process big_stripes/position_17.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_18.00/
subscript gradient
process big_stripes/position_18.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_18.40/
subscript gradient
process big_stripes/position_18.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_18.80/
subscript gradient
process big_stripes/position_18.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_19.20/
subscript gradient
process big_stripes/position_19.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_19.60/
subscript gradient
process big_stripes/position_19.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_20.00/
subscript gradient
process big_stripes/position_20.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_20.40/
subscript gradient
process big_stripes/position_20.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_20.80/
subscript gradient
process big_stripes/position_20.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_21.20/
subscript gradient
process big_stripes/position_21.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_21.60/
subscript gradient
process big_stripes/position_21.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_22.00/
subscript gradient
process big_stripes/position_22.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_22.40/
subscript gradient
process big_stripes/position_22.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_22.80/
subscript gradient
process big_stripes/position_22.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_23.20/
subscript gradient
process big_stripes/position_23.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_23.60/
subscript gradient
process big_stripes/position_23.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_24.00/
subscript gradient
process big_stripes/position_24.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_24.40/
subscript gradient
process big_stripes/position_24.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_24.80/
subscript gradient
process big_stripes/position_24.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_25.20/
subscript gradient
process big_stripes/position_25.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_25.60/
subscript gradient
process big_stripes/position_25.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_26.00/
subscript gradient
process big_stripes/position_26.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_26.40/
subscript gradient
process big_stripes/position_26.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_26.80/
subscript gradient
process big_stripes/position_26.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_27.20/
subscript gradient
process big_stripes/position_27.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_27.60/
subscript gradient
process big_stripes/position_27.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_28.00/
subscript gradient
process big_stripes/position_28.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_28.40/
subscript gradient
process big_stripes/position_28.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_28.80/
subscript gradient
process big_stripes/position_28.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_29.20/
subscript gradient
process big_stripes/position_29.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_29.60/
subscript gradient
process big_stripes/position_29.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_30.00/
subscript gradient
process big_stripes/position_30.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_30.40/
subscript gradient
process big_stripes/position_30.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_30.80/
subscript gradient
process big_stripes/position_30.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_31.20/
subscript gradient
process big_stripes/position_31.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_31.60/
subscript gradient
process big_stripes/position_31.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_32.00/
subscript gradient
process big_stripes/position_32.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_32.40/
subscript gradient
process big_stripes/position_32.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_32.80/
subscript gradient
process big_stripes/position_32.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_33.20/
subscript gradient
process big_stripes/position_33.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_33.60/
subscript gradient
process big_stripes/position_33.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_34.00/
subscript gradient
process big_stripes/position_34.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_34.40/
subscript gradient
process big_stripes/position_34.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_34.80/
subscript gradient
process big_stripes/position_34.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_35.20/
subscript gradient
process big_stripes/position_35.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_35.60/
subscript gradient
process big_stripes/position_35.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_36.00/
subscript gradient
process big_stripes/position_36.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_36.40/
subscript gradient
process big_stripes/position_36.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_36.80/
subscript gradient
process big_stripes/position_36.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_37.20/
subscript gradient
process big_stripes/position_37.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_37.60/
subscript gradient
process big_stripes/position_37.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_38.00/
subscript gradient
process big_stripes/position_38.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_38.40/
subscript gradient
process big_stripes/position_38.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_38.80/
subscript gradient
process big_stripes/position_38.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_39.20/
subscript gradient
process big_stripes/position_39.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_39.60/
subscript gradient
process big_stripes/position_39.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_40.00/
subscript gradient
process big_stripes/position_40.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_40.40/
subscript gradient
process big_stripes/position_40.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_40.80/
subscript gradient
process big_stripes/position_40.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_41.20/
subscript gradient
process big_stripes/position_41.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_41.60/
subscript gradient
process big_stripes/position_41.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_42.00/
subscript gradient
process big_stripes/position_42.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_42.40/
subscript gradient
process big_stripes/position_42.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_42.80/
subscript gradient
process big_stripes/position_42.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_43.20/
subscript gradient
process big_stripes/position_43.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_43.60/
subscript gradient
process big_stripes/position_43.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_44.00/
subscript gradient
process big_stripes/position_44.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_44.40/
subscript gradient
process big_stripes/position_44.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_44.80/
subscript gradient
process big_stripes/position_44.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_45.20/
subscript gradient
process big_stripes/position_45.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_45.60/
subscript gradient
process big_stripes/position_45.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_46.00/
subscript gradient
process big_stripes/position_46.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_46.40/
subscript gradient
process big_stripes/position_46.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_46.80/
subscript gradient
process big_stripes/position_46.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_47.20/
subscript gradient
process big_stripes/position_47.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_47.60/
subscript gradient
process big_stripes/position_47.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_48.00/
subscript gradient
process big_stripes/position_48.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_48.40/
subscript gradient
process big_stripes/position_48.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_48.80/
subscript gradient
process big_stripes/position_48.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_49.20/
subscript gradient
process big_stripes/position_49.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_49.60/
subscript gradient
process big_stripes/position_49.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_50.00/
subscript gradient
process big_stripes/position_50.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_50.40/
subscript gradient
process big_stripes/position_50.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_50.80/
subscript gradient
process big_stripes/position_50.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_51.20/
subscript gradient
process big_stripes/position_51.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_51.60/
subscript gradient
process big_stripes/position_51.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_52.00/
subscript gradient
process big_stripes/position_52.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_52.40/
subscript gradient
process big_stripes/position_52.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_52.80/
subscript gradient
process big_stripes/position_52.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_53.20/
subscript gradient
process big_stripes/position_53.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_53.60/
subscript gradient
process big_stripes/position_53.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_54.00/
subscript gradient
process big_stripes/position_54.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_54.40/
subscript gradient
process big_stripes/position_54.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_54.80/
subscript gradient
process big_stripes/position_54.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_55.20/
subscript gradient
process big_stripes/position_55.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_55.60/
subscript gradient
process big_stripes/position_55.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_56.00/
subscript gradient
process big_stripes/position_56.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_56.40/
subscript gradient
process big_stripes/position_56.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_56.80/
subscript gradient
process big_stripes/position_56.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_57.20/
subscript gradient
process big_stripes/position_57.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_57.60/
subscript gradient
process big_stripes/position_57.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_58.00/
subscript gradient
process big_stripes/position_58.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_58.40/
subscript gradient
process big_stripes/position_58.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_58.80/
subscript gradient
process big_stripes/position_58.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_59.20/
subscript gradient
process big_stripes/position_59.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_59.60/
subscript gradient
process big_stripes/position_59.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_60.00/
subscript gradient
process big_stripes/position_60.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_60.40/
subscript gradient
process big_stripes/position_60.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_60.80/
subscript gradient
process big_stripes/position_60.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_61.20/
subscript gradient
process big_stripes/position_61.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_61.60/
subscript gradient
process big_stripes/position_61.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_62.00/
subscript gradient
process big_stripes/position_62.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_62.40/
subscript gradient
process big_stripes/position_62.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_62.80/
subscript gradient
process big_stripes/position_62.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_63.20/
subscript gradient
process big_stripes/position_63.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_63.60/
subscript gradient
process big_stripes/position_63.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_64.00/
subscript gradient
process big_stripes/position_64.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_64.40/
subscript gradient
process big_stripes/position_64.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_64.80/
subscript gradient
process big_stripes/position_64.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_65.20/
subscript gradient
process big_stripes/position_65.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_65.60/
subscript gradient
process big_stripes/position_65.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_66.00/
subscript gradient
process big_stripes/position_66.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_66.40/
subscript gradient
process big_stripes/position_66.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_66.80/
subscript gradient
process big_stripes/position_66.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_67.20/
subscript gradient
process big_stripes/position_67.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_67.60/
subscript gradient
process big_stripes/position_67.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_68.00/
subscript gradient
process big_stripes/position_68.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_68.40/
subscript gradient
process big_stripes/position_68.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_68.80/
subscript gradient
process big_stripes/position_68.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_69.20/
subscript gradient
process big_stripes/position_69.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_69.60/
subscript gradient
process big_stripes/position_69.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_70.00/
subscript gradient
process big_stripes/position_70.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_70.40/
subscript gradient
process big_stripes/position_70.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_70.80/
subscript gradient
process big_stripes/position_70.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_71.20/
subscript gradient
process big_stripes/position_71.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_71.60/
subscript gradient
process big_stripes/position_71.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_72.00/
subscript gradient
process big_stripes/position_72.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_72.40/
subscript gradient
process big_stripes/position_72.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_72.80/
subscript gradient
process big_stripes/position_72.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_73.20/
subscript gradient
process big_stripes/position_73.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_73.60/
subscript gradient
process big_stripes/position_73.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_74.00/
subscript gradient
process big_stripes/position_74.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_74.40/
subscript gradient
process big_stripes/position_74.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_74.80/
subscript gradient
process big_stripes/position_74.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_75.20/
subscript gradient
process big_stripes/position_75.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_75.60/
subscript gradient
process big_stripes/position_75.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_76.00/
subscript gradient
process big_stripes/position_76.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_76.40/
subscript gradient
process big_stripes/position_76.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_76.80/
subscript gradient
process big_stripes/position_76.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_77.20/
subscript gradient
process big_stripes/position_77.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_77.60/
subscript gradient
process big_stripes/position_77.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_78.00/
subscript gradient
process big_stripes/position_78.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_78.40/
subscript gradient
process big_stripes/position_78.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_78.80/
subscript gradient
process big_stripes/position_78.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_79.20/
subscript gradient
process big_stripes/position_79.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_79.60/
subscript gradient
process big_stripes/position_79.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_80.00/
subscript gradient
process big_stripes/position_80.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_80.40/
subscript gradient
process big_stripes/position_80.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_80.80/
subscript gradient
process big_stripes/position_80.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_81.20/
subscript gradient
process big_stripes/position_81.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_81.60/
subscript gradient
process big_stripes/position_81.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_82.00/
subscript gradient
process big_stripes/position_82.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_82.40/
subscript gradient
process big_stripes/position_82.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_82.80/
subscript gradient
process big_stripes/position_82.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_83.20/
subscript gradient
process big_stripes/position_83.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_83.60/
subscript gradient
process big_stripes/position_83.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_84.00/
subscript gradient
process big_stripes/position_84.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_84.40/
subscript gradient
process big_stripes/position_84.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_84.80/
subscript gradient
process big_stripes/position_84.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_85.20/
subscript gradient
process big_stripes/position_85.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_85.60/
subscript gradient
process big_stripes/position_85.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_86.00/
subscript gradient
process big_stripes/position_86.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_86.40/
subscript gradient
process big_stripes/position_86.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_86.80/
subscript gradient
process big_stripes/position_86.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_87.20/
subscript gradient
process big_stripes/position_87.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_87.60/
subscript gradient
process big_stripes/position_87.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_88.00/
subscript gradient
process big_stripes/position_88.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_88.40/
subscript gradient
process big_stripes/position_88.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_88.80/
subscript gradient
process big_stripes/position_88.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_89.20/
subscript gradient
process big_stripes/position_89.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_89.60/
subscript gradient
process big_stripes/position_89.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_90.00/
subscript gradient
process big_stripes/position_90.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_90.40/
subscript gradient
process big_stripes/position_90.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_90.80/
subscript gradient
process big_stripes/position_90.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_91.20/
subscript gradient
process big_stripes/position_91.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_91.60/
subscript gradient
process big_stripes/position_91.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_92.00/
subscript gradient
process big_stripes/position_92.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_92.40/
subscript gradient
process big_stripes/position_92.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_92.80/
subscript gradient
process big_stripes/position_92.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_93.20/
subscript gradient
process big_stripes/position_93.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_93.60/
subscript gradient
process big_stripes/position_93.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_94.00/
subscript gradient
process big_stripes/position_94.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_94.40/
subscript gradient
process big_stripes/position_94.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_94.80/
subscript gradient
process big_stripes/position_94.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_95.20/
subscript gradient
process big_stripes/position_95.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_95.60/
subscript gradient
process big_stripes/position_95.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_96.00/
subscript gradient
process big_stripes/position_96.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_96.40/
subscript gradient
process big_stripes/position_96.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_96.80/
subscript gradient
process big_stripes/position_96.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_97.20/
subscript gradient
process big_stripes/position_97.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_97.60/
subscript gradient
process big_stripes/position_97.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_98.00/
subscript gradient
process big_stripes/position_98.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_98.40/
subscript gradient
process big_stripes/position_98.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_98.80/
subscript gradient
process big_stripes/position_98.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_99.20/
subscript gradient
process big_stripes/position_99.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_99.60/
subscript gradient
process big_stripes/position_99.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_100.00/
subscript gradient
process big_stripes/position_100.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_100.40/
subscript gradient
process big_stripes/position_100.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_100.80/
subscript gradient
process big_stripes/position_100.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_101.20/
subscript gradient
process big_stripes/position_101.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_101.60/
subscript gradient
process big_stripes/position_101.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_102.00/
subscript gradient
process big_stripes/position_102.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_102.40/
subscript gradient
process big_stripes/position_102.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_102.80/
subscript gradient
process big_stripes/position_102.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_103.20/
subscript gradient
process big_stripes/position_103.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_103.60/
subscript gradient
process big_stripes/position_103.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_104.00/
subscript gradient
process big_stripes/position_104.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_104.40/
subscript gradient
process big_stripes/position_104.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_104.80/
subscript gradient
process big_stripes/position_104.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_105.20/
subscript gradient
process big_stripes/position_105.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_105.60/
subscript gradient
process big_stripes/position_105.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_106.00/
subscript gradient
process big_stripes/position_106.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_106.40/
subscript gradient
process big_stripes/position_106.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_106.80/
subscript gradient
process big_stripes/position_106.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_107.20/
subscript gradient
process big_stripes/position_107.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_107.60/
subscript gradient
process big_stripes/position_107.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_108.00/
subscript gradient
process big_stripes/position_108.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_108.40/
subscript gradient
process big_stripes/position_108.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_108.80/
subscript gradient
process big_stripes/position_108.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_109.20/
subscript gradient
process big_stripes/position_109.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_109.60/
subscript gradient
process big_stripes/position_109.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_110.00/
subscript gradient
process big_stripes/position_110.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_110.40/
subscript gradient
process big_stripes/position_110.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_110.80/
subscript gradient
process big_stripes/position_110.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_111.20/
subscript gradient
process big_stripes/position_111.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_111.60/
subscript gradient
process big_stripes/position_111.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_112.00/
subscript gradient
process big_stripes/position_112.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_112.40/
subscript gradient
process big_stripes/position_112.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_112.80/
subscript gradient
process big_stripes/position_112.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_113.20/
subscript gradient
process big_stripes/position_113.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_113.60/
subscript gradient
process big_stripes/position_113.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_114.00/
subscript gradient
process big_stripes/position_114.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_114.40/
subscript gradient
process big_stripes/position_114.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_114.80/
subscript gradient
process big_stripes/position_114.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_115.20/
subscript gradient
process big_stripes/position_115.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_115.60/
subscript gradient
process big_stripes/position_115.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_116.00/
subscript gradient
process big_stripes/position_116.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_116.40/
subscript gradient
process big_stripes/position_116.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_116.80/
subscript gradient
process big_stripes/position_116.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_117.20/
subscript gradient
process big_stripes/position_117.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_117.60/
subscript gradient
process big_stripes/position_117.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_118.00/
subscript gradient
process big_stripes/position_118.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_118.40/
subscript gradient
process big_stripes/position_118.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_118.80/
subscript gradient
process big_stripes/position_118.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_119.20/
subscript gradient
process big_stripes/position_119.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_119.60/
subscript gradient
process big_stripes/position_119.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_120.00/
subscript gradient
process big_stripes/position_120.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_120.40/
subscript gradient
process big_stripes/position_120.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_120.80/
subscript gradient
process big_stripes/position_120.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_121.20/
subscript gradient
process big_stripes/position_121.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_121.60/
subscript gradient
process big_stripes/position_121.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_122.00/
subscript gradient
process big_stripes/position_122.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_122.40/
subscript gradient
process big_stripes/position_122.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_122.80/
subscript gradient
process big_stripes/position_122.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_123.20/
subscript gradient
process big_stripes/position_123.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_123.60/
subscript gradient
process big_stripes/position_123.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_124.00/
subscript gradient
process big_stripes/position_124.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_124.40/
subscript gradient
process big_stripes/position_124.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_124.80/
subscript gradient
process big_stripes/position_124.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_125.20/
subscript gradient
process big_stripes/position_125.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_125.60/
subscript gradient
process big_stripes/position_125.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_126.00/
subscript gradient
process big_stripes/position_126.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_126.40/
subscript gradient
process big_stripes/position_126.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_126.80/
subscript gradient
process big_stripes/position_126.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_127.20/
subscript gradient
process big_stripes/position_127.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_127.60/
subscript gradient
process big_stripes/position_127.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_128.00/
subscript gradient
process big_stripes/position_128.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_128.40/
subscript gradient
process big_stripes/position_128.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_128.80/
subscript gradient
process big_stripes/position_128.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_129.20/
subscript gradient
process big_stripes/position_129.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_129.60/
subscript gradient
process big_stripes/position_129.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_130.00/
subscript gradient
process big_stripes/position_130.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_130.40/
subscript gradient
process big_stripes/position_130.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_130.80/
subscript gradient
process big_stripes/position_130.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_131.20/
subscript gradient
process big_stripes/position_131.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_131.60/
subscript gradient
process big_stripes/position_131.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_132.00/
subscript gradient
process big_stripes/position_132.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_132.40/
subscript gradient
process big_stripes/position_132.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_132.80/
subscript gradient
process big_stripes/position_132.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_133.20/
subscript gradient
process big_stripes/position_133.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_133.60/
subscript gradient
process big_stripes/position_133.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_134.00/
subscript gradient
process big_stripes/position_134.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_134.40/
subscript gradient
process big_stripes/position_134.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_134.80/
subscript gradient
process big_stripes/position_134.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_135.20/
subscript gradient
process big_stripes/position_135.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_135.60/
subscript gradient
process big_stripes/position_135.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_136.00/
subscript gradient
process big_stripes/position_136.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_136.40/
subscript gradient
process big_stripes/position_136.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_136.80/
subscript gradient
process big_stripes/position_136.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_137.20/
subscript gradient
process big_stripes/position_137.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_137.60/
subscript gradient
process big_stripes/position_137.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_138.00/
subscript gradient
process big_stripes/position_138.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_138.40/
subscript gradient
process big_stripes/position_138.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_138.80/
subscript gradient
process big_stripes/position_138.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_139.20/
subscript gradient
process big_stripes/position_139.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_139.60/
subscript gradient
process big_stripes/position_139.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_140.00/
subscript gradient
process big_stripes/position_140.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_140.40/
subscript gradient
process big_stripes/position_140.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_140.80/
subscript gradient
process big_stripes/position_140.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_141.20/
subscript gradient
process big_stripes/position_141.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_141.60/
subscript gradient
process big_stripes/position_141.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_142.00/
subscript gradient
process big_stripes/position_142.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_142.40/
subscript gradient
process big_stripes/position_142.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_142.80/
subscript gradient
process big_stripes/position_142.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_143.20/
subscript gradient
process big_stripes/position_143.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_143.60/
subscript gradient
process big_stripes/position_143.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_144.00/
subscript gradient
process big_stripes/position_144.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_144.40/
subscript gradient
process big_stripes/position_144.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_144.80/
subscript gradient
process big_stripes/position_144.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_145.20/
subscript gradient
process big_stripes/position_145.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_145.60/
subscript gradient
process big_stripes/position_145.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_146.00/
subscript gradient
process big_stripes/position_146.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_146.40/
subscript gradient
process big_stripes/position_146.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_146.80/
subscript gradient
process big_stripes/position_146.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_147.20/
subscript gradient
process big_stripes/position_147.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_147.60/
subscript gradient
process big_stripes/position_147.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_148.00/
subscript gradient
process big_stripes/position_148.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_148.40/
subscript gradient
process big_stripes/position_148.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_148.80/
subscript gradient
process big_stripes/position_148.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_149.20/
subscript gradient
process big_stripes/position_149.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_149.60/
subscript gradient
process big_stripes/position_149.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_150.00/
subscript gradient
process big_stripes/position_150.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_150.40/
subscript gradient
process big_stripes/position_150.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_150.80/
subscript gradient
process big_stripes/position_150.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_151.20/
subscript gradient
process big_stripes/position_151.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_151.60/
subscript gradient
process big_stripes/position_151.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_152.00/
subscript gradient
process big_stripes/position_152.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_152.40/
subscript gradient
process big_stripes/position_152.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_152.80/
subscript gradient
process big_stripes/position_152.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_153.20/
subscript gradient
process big_stripes/position_153.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_153.60/
subscript gradient
process big_stripes/position_153.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_154.00/
subscript gradient
process big_stripes/position_154.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_154.40/
subscript gradient
process big_stripes/position_154.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_154.80/
subscript gradient
process big_stripes/position_154.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_155.20/
subscript gradient
process big_stripes/position_155.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_155.60/
subscript gradient
process big_stripes/position_155.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_156.00/
subscript gradient
process big_stripes/position_156.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_156.40/
subscript gradient
process big_stripes/position_156.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_156.80/
subscript gradient
process big_stripes/position_156.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_157.20/
subscript gradient
process big_stripes/position_157.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_157.60/
subscript gradient
process big_stripes/position_157.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_158.00/
subscript gradient
process big_stripes/position_158.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_158.40/
subscript gradient
process big_stripes/position_158.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_158.80/
subscript gradient
process big_stripes/position_158.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_159.20/
subscript gradient
process big_stripes/position_159.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_159.60/
subscript gradient
process big_stripes/position_159.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_160.00/
subscript gradient
process big_stripes/position_160.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_160.40/
subscript gradient
process big_stripes/position_160.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_160.80/
subscript gradient
process big_stripes/position_160.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_161.20/
subscript gradient
process big_stripes/position_161.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_161.60/
subscript gradient
process big_stripes/position_161.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_162.00/
subscript gradient
process big_stripes/position_162.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_162.40/
subscript gradient
process big_stripes/position_162.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_162.80/
subscript gradient
process big_stripes/position_162.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_163.20/
subscript gradient
process big_stripes/position_163.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_163.60/
subscript gradient
process big_stripes/position_163.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_164.00/
subscript gradient
process big_stripes/position_164.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_164.40/
subscript gradient
process big_stripes/position_164.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_164.80/
subscript gradient
process big_stripes/position_164.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_165.20/
subscript gradient
process big_stripes/position_165.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_165.60/
subscript gradient
process big_stripes/position_165.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_166.00/
subscript gradient
process big_stripes/position_166.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_166.40/
subscript gradient
process big_stripes/position_166.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_166.80/
subscript gradient
process big_stripes/position_166.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_167.20/
subscript gradient
process big_stripes/position_167.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_167.60/
subscript gradient
process big_stripes/position_167.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_168.00/
subscript gradient
process big_stripes/position_168.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_168.40/
subscript gradient
process big_stripes/position_168.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_168.80/
subscript gradient
process big_stripes/position_168.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_169.20/
subscript gradient
process big_stripes/position_169.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_169.60/
subscript gradient
process big_stripes/position_169.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_170.00/
subscript gradient
process big_stripes/position_170.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_170.40/
subscript gradient
process big_stripes/position_170.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_170.80/
subscript gradient
process big_stripes/position_170.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_171.20/
subscript gradient
process big_stripes/position_171.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_171.60/
subscript gradient
process big_stripes/position_171.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_172.00/
subscript gradient
process big_stripes/position_172.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_172.40/
subscript gradient
process big_stripes/position_172.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_172.80/
subscript gradient
process big_stripes/position_172.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_173.20/
subscript gradient
process big_stripes/position_173.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_173.60/
subscript gradient
process big_stripes/position_173.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_174.00/
subscript gradient
process big_stripes/position_174.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_174.40/
subscript gradient
process big_stripes/position_174.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_174.80/
subscript gradient
process big_stripes/position_174.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_175.20/
subscript gradient
process big_stripes/position_175.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_175.60/
subscript gradient
process big_stripes/position_175.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_176.00/
subscript gradient
process big_stripes/position_176.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_176.40/
subscript gradient
process big_stripes/position_176.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_176.80/
subscript gradient
process big_stripes/position_176.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_177.20/
subscript gradient
process big_stripes/position_177.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_177.60/
subscript gradient
process big_stripes/position_177.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_178.00/
subscript gradient
process big_stripes/position_178.00/
status
move 0.40
delay 2.000
prefix big_stripes/position_178.40/
subscript gradient
process big_stripes/position_178.40/
status
move 0.40
delay 2.000
prefix big_stripes/position_178.80/
subscript gradient
process big_stripes/position_178.80/
status
move 0.40
delay 2.000
prefix big_stripes/position_179.20/
subscript gradient
process big_stripes/position_179.20/
status
move 0.40
delay 2.000
prefix big_stripes/position_179.60/
subscript gradient
process big_stripes/position_179.60/
status
move 0.40
delay 2.000
prefix big_stripes/position_180.00/
subscript gradient
process big_stripes/position_180.00/
status
