prefix bigger_stripes/
prefix bigger_stripes/position_0.00/
subscript gradient
process bigger_stripes/position_0.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_0.20/
subscript gradient
process bigger_stripes/position_0.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_0.40/
subscript gradient
process bigger_stripes/position_0.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_0.60/
subscript gradient
process bigger_stripes/position_0.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_0.80/
subscript gradient
process bigger_stripes/position_0.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_1.00/
subscript gradient
process bigger_stripes/position_1.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_1.20/
subscript gradient
process bigger_stripes/position_1.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_1.40/
subscript gradient
process bigger_stripes/position_1.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_1.60/
subscript gradient
process bigger_stripes/position_1.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_1.80/
subscript gradient
process bigger_stripes/position_1.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_2.00/
subscript gradient
process bigger_stripes/position_2.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_2.20/
subscript gradient
process bigger_stripes/position_2.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_2.40/
subscript gradient
process bigger_stripes/position_2.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_2.60/
subscript gradient
process bigger_stripes/position_2.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_2.80/
subscript gradient
process bigger_stripes/position_2.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_3.00/
subscript gradient
process bigger_stripes/position_3.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_3.20/
subscript gradient
process bigger_stripes/position_3.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_3.40/
subscript gradient
process bigger_stripes/position_3.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_3.60/
subscript gradient
process bigger_stripes/position_3.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_3.80/
subscript gradient
process bigger_stripes/position_3.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_4.00/
subscript gradient
process bigger_stripes/position_4.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_4.20/
subscript gradient
process bigger_stripes/position_4.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_4.40/
subscript gradient
process bigger_stripes/position_4.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_4.60/
subscript gradient
process bigger_stripes/position_4.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_4.80/
subscript gradient
process bigger_stripes/position_4.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_5.00/
subscript gradient
process bigger_stripes/position_5.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_5.20/
subscript gradient
process bigger_stripes/position_5.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_5.40/
subscript gradient
process bigger_stripes/position_5.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_5.60/
subscript gradient
process bigger_stripes/position_5.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_5.80/
subscript gradient
process bigger_stripes/position_5.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_6.00/
subscript gradient
process bigger_stripes/position_6.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_6.20/
subscript gradient
process bigger_stripes/position_6.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_6.40/
subscript gradient
process bigger_stripes/position_6.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_6.60/
subscript gradient
process bigger_stripes/position_6.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_6.80/
subscript gradient
process bigger_stripes/position_6.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_7.00/
subscript gradient
process bigger_stripes/position_7.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_7.20/
subscript gradient
process bigger_stripes/position_7.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_7.40/
subscript gradient
process bigger_stripes/position_7.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_7.60/
subscript gradient
process bigger_stripes/position_7.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_7.80/
subscript gradient
process bigger_stripes/position_7.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_8.00/
subscript gradient
process bigger_stripes/position_8.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_8.20/
subscript gradient
process bigger_stripes/position_8.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_8.40/
subscript gradient
process bigger_stripes/position_8.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_8.60/
subscript gradient
process bigger_stripes/position_8.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_8.80/
subscript gradient
process bigger_stripes/position_8.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_9.00/
subscript gradient
process bigger_stripes/position_9.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_9.20/
subscript gradient
process bigger_stripes/position_9.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_9.40/
subscript gradient
process bigger_stripes/position_9.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_9.60/
subscript gradient
process bigger_stripes/position_9.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_9.80/
subscript gradient
process bigger_stripes/position_9.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_10.00/
subscript gradient
process bigger_stripes/position_10.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_10.20/
subscript gradient
process bigger_stripes/position_10.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_10.40/
subscript gradient
process bigger_stripes/position_10.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_10.60/
subscript gradient
process bigger_stripes/position_10.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_10.80/
subscript gradient
process bigger_stripes/position_10.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_11.00/
subscript gradient
process bigger_stripes/position_11.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_11.20/
subscript gradient
process bigger_stripes/position_11.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_11.40/
subscript gradient
process bigger_stripes/position_11.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_11.60/
subscript gradient
process bigger_stripes/position_11.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_11.80/
subscript gradient
process bigger_stripes/position_11.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_12.00/
subscript gradient
process bigger_stripes/position_12.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_12.20/
subscript gradient
process bigger_stripes/position_12.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_12.40/
subscript gradient
process bigger_stripes/position_12.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_12.60/
subscript gradient
process bigger_stripes/position_12.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_12.80/
subscript gradient
process bigger_stripes/position_12.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_13.00/
subscript gradient
process bigger_stripes/position_13.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_13.20/
subscript gradient
process bigger_stripes/position_13.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_13.40/
subscript gradient
process bigger_stripes/position_13.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_13.60/
subscript gradient
process bigger_stripes/position_13.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_13.80/
subscript gradient
process bigger_stripes/position_13.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_14.00/
subscript gradient
process bigger_stripes/position_14.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_14.20/
subscript gradient
process bigger_stripes/position_14.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_14.40/
subscript gradient
process bigger_stripes/position_14.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_14.60/
subscript gradient
process bigger_stripes/position_14.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_14.80/
subscript gradient
process bigger_stripes/position_14.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_15.00/
subscript gradient
process bigger_stripes/position_15.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_15.20/
subscript gradient
process bigger_stripes/position_15.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_15.40/
subscript gradient
process bigger_stripes/position_15.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_15.60/
subscript gradient
process bigger_stripes/position_15.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_15.80/
subscript gradient
process bigger_stripes/position_15.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_16.00/
subscript gradient
process bigger_stripes/position_16.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_16.20/
subscript gradient
process bigger_stripes/position_16.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_16.40/
subscript gradient
process bigger_stripes/position_16.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_16.60/
subscript gradient
process bigger_stripes/position_16.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_16.80/
subscript gradient
process bigger_stripes/position_16.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_17.00/
subscript gradient
process bigger_stripes/position_17.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_17.20/
subscript gradient
process bigger_stripes/position_17.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_17.40/
subscript gradient
process bigger_stripes/position_17.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_17.60/
subscript gradient
process bigger_stripes/position_17.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_17.80/
subscript gradient
process bigger_stripes/position_17.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_18.00/
subscript gradient
process bigger_stripes/position_18.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_18.20/
subscript gradient
process bigger_stripes/position_18.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_18.40/
subscript gradient
process bigger_stripes/position_18.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_18.60/
subscript gradient
process bigger_stripes/position_18.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_18.80/
subscript gradient
process bigger_stripes/position_18.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_19.00/
subscript gradient
process bigger_stripes/position_19.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_19.20/
subscript gradient
process bigger_stripes/position_19.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_19.40/
subscript gradient
process bigger_stripes/position_19.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_19.60/
subscript gradient
process bigger_stripes/position_19.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_19.80/
subscript gradient
process bigger_stripes/position_19.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_20.00/
subscript gradient
process bigger_stripes/position_20.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_20.20/
subscript gradient
process bigger_stripes/position_20.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_20.40/
subscript gradient
process bigger_stripes/position_20.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_20.60/
subscript gradient
process bigger_stripes/position_20.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_20.80/
subscript gradient
process bigger_stripes/position_20.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_21.00/
subscript gradient
process bigger_stripes/position_21.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_21.20/
subscript gradient
process bigger_stripes/position_21.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_21.40/
subscript gradient
process bigger_stripes/position_21.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_21.60/
subscript gradient
process bigger_stripes/position_21.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_21.80/
subscript gradient
process bigger_stripes/position_21.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_22.00/
subscript gradient
process bigger_stripes/position_22.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_22.20/
subscript gradient
process bigger_stripes/position_22.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_22.40/
subscript gradient
process bigger_stripes/position_22.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_22.60/
subscript gradient
process bigger_stripes/position_22.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_22.80/
subscript gradient
process bigger_stripes/position_22.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_23.00/
subscript gradient
process bigger_stripes/position_23.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_23.20/
subscript gradient
process bigger_stripes/position_23.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_23.40/
subscript gradient
process bigger_stripes/position_23.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_23.60/
subscript gradient
process bigger_stripes/position_23.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_23.80/
subscript gradient
process bigger_stripes/position_23.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_24.00/
subscript gradient
process bigger_stripes/position_24.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_24.20/
subscript gradient
process bigger_stripes/position_24.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_24.40/
subscript gradient
process bigger_stripes/position_24.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_24.60/
subscript gradient
process bigger_stripes/position_24.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_24.80/
subscript gradient
process bigger_stripes/position_24.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_25.00/
subscript gradient
process bigger_stripes/position_25.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_25.20/
subscript gradient
process bigger_stripes/position_25.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_25.40/
subscript gradient
process bigger_stripes/position_25.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_25.60/
subscript gradient
process bigger_stripes/position_25.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_25.80/
subscript gradient
process bigger_stripes/position_25.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_26.00/
subscript gradient
process bigger_stripes/position_26.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_26.20/
subscript gradient
process bigger_stripes/position_26.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_26.40/
subscript gradient
process bigger_stripes/position_26.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_26.60/
subscript gradient
process bigger_stripes/position_26.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_26.80/
subscript gradient
process bigger_stripes/position_26.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_27.00/
subscript gradient
process bigger_stripes/position_27.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_27.20/
subscript gradient
process bigger_stripes/position_27.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_27.40/
subscript gradient
process bigger_stripes/position_27.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_27.60/
subscript gradient
process bigger_stripes/position_27.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_27.80/
subscript gradient
process bigger_stripes/position_27.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_28.00/
subscript gradient
process bigger_stripes/position_28.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_28.20/
subscript gradient
process bigger_stripes/position_28.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_28.40/
subscript gradient
process bigger_stripes/position_28.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_28.60/
subscript gradient
process bigger_stripes/position_28.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_28.80/
subscript gradient
process bigger_stripes/position_28.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_29.00/
subscript gradient
process bigger_stripes/position_29.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_29.20/
subscript gradient
process bigger_stripes/position_29.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_29.40/
subscript gradient
process bigger_stripes/position_29.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_29.60/
subscript gradient
process bigger_stripes/position_29.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_29.80/
subscript gradient
process bigger_stripes/position_29.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_30.00/
subscript gradient
process bigger_stripes/position_30.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_30.20/
subscript gradient
process bigger_stripes/position_30.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_30.40/
subscript gradient
process bigger_stripes/position_30.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_30.60/
subscript gradient
process bigger_stripes/position_30.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_30.80/
subscript gradient
process bigger_stripes/position_30.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_31.00/
subscript gradient
process bigger_stripes/position_31.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_31.20/
subscript gradient
process bigger_stripes/position_31.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_31.40/
subscript gradient
process bigger_stripes/position_31.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_31.60/
subscript gradient
process bigger_stripes/position_31.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_31.80/
subscript gradient
process bigger_stripes/position_31.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_32.00/
subscript gradient
process bigger_stripes/position_32.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_32.20/
subscript gradient
process bigger_stripes/position_32.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_32.40/
subscript gradient
process bigger_stripes/position_32.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_32.60/
subscript gradient
process bigger_stripes/position_32.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_32.80/
subscript gradient
process bigger_stripes/position_32.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_33.00/
subscript gradient
process bigger_stripes/position_33.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_33.20/
subscript gradient
process bigger_stripes/position_33.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_33.40/
subscript gradient
process bigger_stripes/position_33.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_33.60/
subscript gradient
process bigger_stripes/position_33.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_33.80/
subscript gradient
process bigger_stripes/position_33.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_34.00/
subscript gradient
process bigger_stripes/position_34.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_34.20/
subscript gradient
process bigger_stripes/position_34.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_34.40/
subscript gradient
process bigger_stripes/position_34.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_34.60/
subscript gradient
process bigger_stripes/position_34.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_34.80/
subscript gradient
process bigger_stripes/position_34.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_35.00/
subscript gradient
process bigger_stripes/position_35.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_35.20/
subscript gradient
process bigger_stripes/position_35.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_35.40/
subscript gradient
process bigger_stripes/position_35.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_35.60/
subscript gradient
process bigger_stripes/position_35.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_35.80/
subscript gradient
process bigger_stripes/position_35.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_36.00/
subscript gradient
process bigger_stripes/position_36.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_36.20/
subscript gradient
process bigger_stripes/position_36.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_36.40/
subscript gradient
process bigger_stripes/position_36.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_36.60/
subscript gradient
process bigger_stripes/position_36.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_36.80/
subscript gradient
process bigger_stripes/position_36.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_37.00/
subscript gradient
process bigger_stripes/position_37.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_37.20/
subscript gradient
process bigger_stripes/position_37.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_37.40/
subscript gradient
process bigger_stripes/position_37.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_37.60/
subscript gradient
process bigger_stripes/position_37.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_37.80/
subscript gradient
process bigger_stripes/position_37.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_38.00/
subscript gradient
process bigger_stripes/position_38.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_38.20/
subscript gradient
process bigger_stripes/position_38.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_38.40/
subscript gradient
process bigger_stripes/position_38.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_38.60/
subscript gradient
process bigger_stripes/position_38.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_38.80/
subscript gradient
process bigger_stripes/position_38.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_39.00/
subscript gradient
process bigger_stripes/position_39.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_39.20/
subscript gradient
process bigger_stripes/position_39.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_39.40/
subscript gradient
process bigger_stripes/position_39.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_39.60/
subscript gradient
process bigger_stripes/position_39.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_39.80/
subscript gradient
process bigger_stripes/position_39.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_40.00/
subscript gradient
process bigger_stripes/position_40.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_40.20/
subscript gradient
process bigger_stripes/position_40.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_40.40/
subscript gradient
process bigger_stripes/position_40.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_40.60/
subscript gradient
process bigger_stripes/position_40.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_40.80/
subscript gradient
process bigger_stripes/position_40.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_41.00/
subscript gradient
process bigger_stripes/position_41.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_41.20/
subscript gradient
process bigger_stripes/position_41.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_41.40/
subscript gradient
process bigger_stripes/position_41.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_41.60/
subscript gradient
process bigger_stripes/position_41.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_41.80/
subscript gradient
process bigger_stripes/position_41.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_42.00/
subscript gradient
process bigger_stripes/position_42.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_42.20/
subscript gradient
process bigger_stripes/position_42.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_42.40/
subscript gradient
process bigger_stripes/position_42.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_42.60/
subscript gradient
process bigger_stripes/position_42.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_42.80/
subscript gradient
process bigger_stripes/position_42.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_43.00/
subscript gradient
process bigger_stripes/position_43.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_43.20/
subscript gradient
process bigger_stripes/position_43.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_43.40/
subscript gradient
process bigger_stripes/position_43.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_43.60/
subscript gradient
process bigger_stripes/position_43.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_43.80/
subscript gradient
process bigger_stripes/position_43.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_44.00/
subscript gradient
process bigger_stripes/position_44.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_44.20/
subscript gradient
process bigger_stripes/position_44.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_44.40/
subscript gradient
process bigger_stripes/position_44.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_44.60/
subscript gradient
process bigger_stripes/position_44.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_44.80/
subscript gradient
process bigger_stripes/position_44.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_45.00/
subscript gradient
process bigger_stripes/position_45.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_45.20/
subscript gradient
process bigger_stripes/position_45.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_45.40/
subscript gradient
process bigger_stripes/position_45.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_45.60/
subscript gradient
process bigger_stripes/position_45.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_45.80/
subscript gradient
process bigger_stripes/position_45.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_46.00/
subscript gradient
process bigger_stripes/position_46.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_46.20/
subscript gradient
process bigger_stripes/position_46.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_46.40/
subscript gradient
process bigger_stripes/position_46.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_46.60/
subscript gradient
process bigger_stripes/position_46.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_46.80/
subscript gradient
process bigger_stripes/position_46.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_47.00/
subscript gradient
process bigger_stripes/position_47.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_47.20/
subscript gradient
process bigger_stripes/position_47.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_47.40/
subscript gradient
process bigger_stripes/position_47.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_47.60/
subscript gradient
process bigger_stripes/position_47.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_47.80/
subscript gradient
process bigger_stripes/position_47.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_48.00/
subscript gradient
process bigger_stripes/position_48.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_48.20/
subscript gradient
process bigger_stripes/position_48.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_48.40/
subscript gradient
process bigger_stripes/position_48.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_48.60/
subscript gradient
process bigger_stripes/position_48.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_48.80/
subscript gradient
process bigger_stripes/position_48.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_49.00/
subscript gradient
process bigger_stripes/position_49.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_49.20/
subscript gradient
process bigger_stripes/position_49.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_49.40/
subscript gradient
process bigger_stripes/position_49.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_49.60/
subscript gradient
process bigger_stripes/position_49.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_49.80/
subscript gradient
process bigger_stripes/position_49.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_50.00/
subscript gradient
process bigger_stripes/position_50.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_50.20/
subscript gradient
process bigger_stripes/position_50.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_50.40/
subscript gradient
process bigger_stripes/position_50.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_50.60/
subscript gradient
process bigger_stripes/position_50.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_50.80/
subscript gradient
process bigger_stripes/position_50.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_51.00/
subscript gradient
process bigger_stripes/position_51.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_51.20/
subscript gradient
process bigger_stripes/position_51.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_51.40/
subscript gradient
process bigger_stripes/position_51.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_51.60/
subscript gradient
process bigger_stripes/position_51.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_51.80/
subscript gradient
process bigger_stripes/position_51.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_52.00/
subscript gradient
process bigger_stripes/position_52.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_52.20/
subscript gradient
process bigger_stripes/position_52.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_52.40/
subscript gradient
process bigger_stripes/position_52.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_52.60/
subscript gradient
process bigger_stripes/position_52.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_52.80/
subscript gradient
process bigger_stripes/position_52.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_53.00/
subscript gradient
process bigger_stripes/position_53.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_53.20/
subscript gradient
process bigger_stripes/position_53.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_53.40/
subscript gradient
process bigger_stripes/position_53.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_53.60/
subscript gradient
process bigger_stripes/position_53.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_53.80/
subscript gradient
process bigger_stripes/position_53.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_54.00/
subscript gradient
process bigger_stripes/position_54.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_54.20/
subscript gradient
process bigger_stripes/position_54.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_54.40/
subscript gradient
process bigger_stripes/position_54.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_54.60/
subscript gradient
process bigger_stripes/position_54.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_54.80/
subscript gradient
process bigger_stripes/position_54.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_55.00/
subscript gradient
process bigger_stripes/position_55.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_55.20/
subscript gradient
process bigger_stripes/position_55.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_55.40/
subscript gradient
process bigger_stripes/position_55.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_55.60/
subscript gradient
process bigger_stripes/position_55.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_55.80/
subscript gradient
process bigger_stripes/position_55.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_56.00/
subscript gradient
process bigger_stripes/position_56.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_56.20/
subscript gradient
process bigger_stripes/position_56.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_56.40/
subscript gradient
process bigger_stripes/position_56.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_56.60/
subscript gradient
process bigger_stripes/position_56.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_56.80/
subscript gradient
process bigger_stripes/position_56.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_57.00/
subscript gradient
process bigger_stripes/position_57.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_57.20/
subscript gradient
process bigger_stripes/position_57.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_57.40/
subscript gradient
process bigger_stripes/position_57.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_57.60/
subscript gradient
process bigger_stripes/position_57.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_57.80/
subscript gradient
process bigger_stripes/position_57.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_58.00/
subscript gradient
process bigger_stripes/position_58.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_58.20/
subscript gradient
process bigger_stripes/position_58.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_58.40/
subscript gradient
process bigger_stripes/position_58.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_58.60/
subscript gradient
process bigger_stripes/position_58.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_58.80/
subscript gradient
process bigger_stripes/position_58.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_59.00/
subscript gradient
process bigger_stripes/position_59.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_59.20/
subscript gradient
process bigger_stripes/position_59.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_59.40/
subscript gradient
process bigger_stripes/position_59.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_59.60/
subscript gradient
process bigger_stripes/position_59.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_59.80/
subscript gradient
process bigger_stripes/position_59.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_60.00/
subscript gradient
process bigger_stripes/position_60.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_60.20/
subscript gradient
process bigger_stripes/position_60.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_60.40/
subscript gradient
process bigger_stripes/position_60.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_60.60/
subscript gradient
process bigger_stripes/position_60.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_60.80/
subscript gradient
process bigger_stripes/position_60.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_61.00/
subscript gradient
process bigger_stripes/position_61.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_61.20/
subscript gradient
process bigger_stripes/position_61.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_61.40/
subscript gradient
process bigger_stripes/position_61.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_61.60/
subscript gradient
process bigger_stripes/position_61.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_61.80/
subscript gradient
process bigger_stripes/position_61.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_62.00/
subscript gradient
process bigger_stripes/position_62.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_62.20/
subscript gradient
process bigger_stripes/position_62.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_62.40/
subscript gradient
process bigger_stripes/position_62.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_62.60/
subscript gradient
process bigger_stripes/position_62.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_62.80/
subscript gradient
process bigger_stripes/position_62.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_63.00/
subscript gradient
process bigger_stripes/position_63.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_63.20/
subscript gradient
process bigger_stripes/position_63.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_63.40/
subscript gradient
process bigger_stripes/position_63.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_63.60/
subscript gradient
process bigger_stripes/position_63.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_63.80/
subscript gradient
process bigger_stripes/position_63.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_64.00/
subscript gradient
process bigger_stripes/position_64.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_64.20/
subscript gradient
process bigger_stripes/position_64.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_64.40/
subscript gradient
process bigger_stripes/position_64.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_64.60/
subscript gradient
process bigger_stripes/position_64.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_64.80/
subscript gradient
process bigger_stripes/position_64.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_65.00/
subscript gradient
process bigger_stripes/position_65.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_65.20/
subscript gradient
process bigger_stripes/position_65.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_65.40/
subscript gradient
process bigger_stripes/position_65.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_65.60/
subscript gradient
process bigger_stripes/position_65.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_65.80/
subscript gradient
process bigger_stripes/position_65.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_66.00/
subscript gradient
process bigger_stripes/position_66.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_66.20/
subscript gradient
process bigger_stripes/position_66.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_66.40/
subscript gradient
process bigger_stripes/position_66.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_66.60/
subscript gradient
process bigger_stripes/position_66.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_66.80/
subscript gradient
process bigger_stripes/position_66.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_67.00/
subscript gradient
process bigger_stripes/position_67.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_67.20/
subscript gradient
process bigger_stripes/position_67.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_67.40/
subscript gradient
process bigger_stripes/position_67.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_67.60/
subscript gradient
process bigger_stripes/position_67.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_67.80/
subscript gradient
process bigger_stripes/position_67.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_68.00/
subscript gradient
process bigger_stripes/position_68.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_68.20/
subscript gradient
process bigger_stripes/position_68.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_68.40/
subscript gradient
process bigger_stripes/position_68.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_68.60/
subscript gradient
process bigger_stripes/position_68.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_68.80/
subscript gradient
process bigger_stripes/position_68.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_69.00/
subscript gradient
process bigger_stripes/position_69.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_69.20/
subscript gradient
process bigger_stripes/position_69.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_69.40/
subscript gradient
process bigger_stripes/position_69.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_69.60/
subscript gradient
process bigger_stripes/position_69.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_69.80/
subscript gradient
process bigger_stripes/position_69.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_70.00/
subscript gradient
process bigger_stripes/position_70.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_70.20/
subscript gradient
process bigger_stripes/position_70.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_70.40/
subscript gradient
process bigger_stripes/position_70.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_70.60/
subscript gradient
process bigger_stripes/position_70.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_70.80/
subscript gradient
process bigger_stripes/position_70.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_71.00/
subscript gradient
process bigger_stripes/position_71.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_71.20/
subscript gradient
process bigger_stripes/position_71.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_71.40/
subscript gradient
process bigger_stripes/position_71.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_71.60/
subscript gradient
process bigger_stripes/position_71.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_71.80/
subscript gradient
process bigger_stripes/position_71.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_72.00/
subscript gradient
process bigger_stripes/position_72.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_72.20/
subscript gradient
process bigger_stripes/position_72.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_72.40/
subscript gradient
process bigger_stripes/position_72.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_72.60/
subscript gradient
process bigger_stripes/position_72.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_72.80/
subscript gradient
process bigger_stripes/position_72.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_73.00/
subscript gradient
process bigger_stripes/position_73.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_73.20/
subscript gradient
process bigger_stripes/position_73.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_73.40/
subscript gradient
process bigger_stripes/position_73.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_73.60/
subscript gradient
process bigger_stripes/position_73.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_73.80/
subscript gradient
process bigger_stripes/position_73.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_74.00/
subscript gradient
process bigger_stripes/position_74.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_74.20/
subscript gradient
process bigger_stripes/position_74.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_74.40/
subscript gradient
process bigger_stripes/position_74.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_74.60/
subscript gradient
process bigger_stripes/position_74.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_74.80/
subscript gradient
process bigger_stripes/position_74.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_75.00/
subscript gradient
process bigger_stripes/position_75.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_75.20/
subscript gradient
process bigger_stripes/position_75.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_75.40/
subscript gradient
process bigger_stripes/position_75.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_75.60/
subscript gradient
process bigger_stripes/position_75.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_75.80/
subscript gradient
process bigger_stripes/position_75.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_76.00/
subscript gradient
process bigger_stripes/position_76.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_76.20/
subscript gradient
process bigger_stripes/position_76.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_76.40/
subscript gradient
process bigger_stripes/position_76.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_76.60/
subscript gradient
process bigger_stripes/position_76.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_76.80/
subscript gradient
process bigger_stripes/position_76.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_77.00/
subscript gradient
process bigger_stripes/position_77.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_77.20/
subscript gradient
process bigger_stripes/position_77.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_77.40/
subscript gradient
process bigger_stripes/position_77.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_77.60/
subscript gradient
process bigger_stripes/position_77.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_77.80/
subscript gradient
process bigger_stripes/position_77.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_78.00/
subscript gradient
process bigger_stripes/position_78.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_78.20/
subscript gradient
process bigger_stripes/position_78.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_78.40/
subscript gradient
process bigger_stripes/position_78.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_78.60/
subscript gradient
process bigger_stripes/position_78.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_78.80/
subscript gradient
process bigger_stripes/position_78.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_79.00/
subscript gradient
process bigger_stripes/position_79.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_79.20/
subscript gradient
process bigger_stripes/position_79.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_79.40/
subscript gradient
process bigger_stripes/position_79.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_79.60/
subscript gradient
process bigger_stripes/position_79.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_79.80/
subscript gradient
process bigger_stripes/position_79.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_80.00/
subscript gradient
process bigger_stripes/position_80.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_80.20/
subscript gradient
process bigger_stripes/position_80.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_80.40/
subscript gradient
process bigger_stripes/position_80.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_80.60/
subscript gradient
process bigger_stripes/position_80.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_80.80/
subscript gradient
process bigger_stripes/position_80.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_81.00/
subscript gradient
process bigger_stripes/position_81.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_81.20/
subscript gradient
process bigger_stripes/position_81.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_81.40/
subscript gradient
process bigger_stripes/position_81.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_81.60/
subscript gradient
process bigger_stripes/position_81.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_81.80/
subscript gradient
process bigger_stripes/position_81.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_82.00/
subscript gradient
process bigger_stripes/position_82.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_82.20/
subscript gradient
process bigger_stripes/position_82.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_82.40/
subscript gradient
process bigger_stripes/position_82.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_82.60/
subscript gradient
process bigger_stripes/position_82.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_82.80/
subscript gradient
process bigger_stripes/position_82.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_83.00/
subscript gradient
process bigger_stripes/position_83.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_83.20/
subscript gradient
process bigger_stripes/position_83.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_83.40/
subscript gradient
process bigger_stripes/position_83.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_83.60/
subscript gradient
process bigger_stripes/position_83.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_83.80/
subscript gradient
process bigger_stripes/position_83.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_84.00/
subscript gradient
process bigger_stripes/position_84.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_84.20/
subscript gradient
process bigger_stripes/position_84.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_84.40/
subscript gradient
process bigger_stripes/position_84.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_84.60/
subscript gradient
process bigger_stripes/position_84.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_84.80/
subscript gradient
process bigger_stripes/position_84.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_85.00/
subscript gradient
process bigger_stripes/position_85.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_85.20/
subscript gradient
process bigger_stripes/position_85.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_85.40/
subscript gradient
process bigger_stripes/position_85.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_85.60/
subscript gradient
process bigger_stripes/position_85.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_85.80/
subscript gradient
process bigger_stripes/position_85.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_86.00/
subscript gradient
process bigger_stripes/position_86.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_86.20/
subscript gradient
process bigger_stripes/position_86.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_86.40/
subscript gradient
process bigger_stripes/position_86.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_86.60/
subscript gradient
process bigger_stripes/position_86.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_86.80/
subscript gradient
process bigger_stripes/position_86.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_87.00/
subscript gradient
process bigger_stripes/position_87.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_87.20/
subscript gradient
process bigger_stripes/position_87.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_87.40/
subscript gradient
process bigger_stripes/position_87.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_87.60/
subscript gradient
process bigger_stripes/position_87.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_87.80/
subscript gradient
process bigger_stripes/position_87.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_88.00/
subscript gradient
process bigger_stripes/position_88.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_88.20/
subscript gradient
process bigger_stripes/position_88.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_88.40/
subscript gradient
process bigger_stripes/position_88.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_88.60/
subscript gradient
process bigger_stripes/position_88.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_88.80/
subscript gradient
process bigger_stripes/position_88.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_89.00/
subscript gradient
process bigger_stripes/position_89.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_89.20/
subscript gradient
process bigger_stripes/position_89.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_89.40/
subscript gradient
process bigger_stripes/position_89.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_89.60/
subscript gradient
process bigger_stripes/position_89.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_89.80/
subscript gradient
process bigger_stripes/position_89.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_90.00/
subscript gradient
process bigger_stripes/position_90.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_90.20/
subscript gradient
process bigger_stripes/position_90.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_90.40/
subscript gradient
process bigger_stripes/position_90.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_90.60/
subscript gradient
process bigger_stripes/position_90.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_90.80/
subscript gradient
process bigger_stripes/position_90.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_91.00/
subscript gradient
process bigger_stripes/position_91.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_91.20/
subscript gradient
process bigger_stripes/position_91.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_91.40/
subscript gradient
process bigger_stripes/position_91.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_91.60/
subscript gradient
process bigger_stripes/position_91.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_91.80/
subscript gradient
process bigger_stripes/position_91.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_92.00/
subscript gradient
process bigger_stripes/position_92.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_92.20/
subscript gradient
process bigger_stripes/position_92.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_92.40/
subscript gradient
process bigger_stripes/position_92.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_92.60/
subscript gradient
process bigger_stripes/position_92.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_92.80/
subscript gradient
process bigger_stripes/position_92.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_93.00/
subscript gradient
process bigger_stripes/position_93.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_93.20/
subscript gradient
process bigger_stripes/position_93.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_93.40/
subscript gradient
process bigger_stripes/position_93.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_93.60/
subscript gradient
process bigger_stripes/position_93.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_93.80/
subscript gradient
process bigger_stripes/position_93.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_94.00/
subscript gradient
process bigger_stripes/position_94.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_94.20/
subscript gradient
process bigger_stripes/position_94.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_94.40/
subscript gradient
process bigger_stripes/position_94.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_94.60/
subscript gradient
process bigger_stripes/position_94.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_94.80/
subscript gradient
process bigger_stripes/position_94.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_95.00/
subscript gradient
process bigger_stripes/position_95.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_95.20/
subscript gradient
process bigger_stripes/position_95.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_95.40/
subscript gradient
process bigger_stripes/position_95.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_95.60/
subscript gradient
process bigger_stripes/position_95.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_95.80/
subscript gradient
process bigger_stripes/position_95.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_96.00/
subscript gradient
process bigger_stripes/position_96.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_96.20/
subscript gradient
process bigger_stripes/position_96.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_96.40/
subscript gradient
process bigger_stripes/position_96.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_96.60/
subscript gradient
process bigger_stripes/position_96.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_96.80/
subscript gradient
process bigger_stripes/position_96.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_97.00/
subscript gradient
process bigger_stripes/position_97.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_97.20/
subscript gradient
process bigger_stripes/position_97.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_97.40/
subscript gradient
process bigger_stripes/position_97.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_97.60/
subscript gradient
process bigger_stripes/position_97.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_97.80/
subscript gradient
process bigger_stripes/position_97.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_98.00/
subscript gradient
process bigger_stripes/position_98.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_98.20/
subscript gradient
process bigger_stripes/position_98.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_98.40/
subscript gradient
process bigger_stripes/position_98.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_98.60/
subscript gradient
process bigger_stripes/position_98.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_98.80/
subscript gradient
process bigger_stripes/position_98.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_99.00/
subscript gradient
process bigger_stripes/position_99.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_99.20/
subscript gradient
process bigger_stripes/position_99.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_99.40/
subscript gradient
process bigger_stripes/position_99.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_99.60/
subscript gradient
process bigger_stripes/position_99.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_99.80/
subscript gradient
process bigger_stripes/position_99.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_100.00/
subscript gradient
process bigger_stripes/position_100.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_100.20/
subscript gradient
process bigger_stripes/position_100.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_100.40/
subscript gradient
process bigger_stripes/position_100.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_100.60/
subscript gradient
process bigger_stripes/position_100.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_100.80/
subscript gradient
process bigger_stripes/position_100.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_101.00/
subscript gradient
process bigger_stripes/position_101.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_101.20/
subscript gradient
process bigger_stripes/position_101.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_101.40/
subscript gradient
process bigger_stripes/position_101.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_101.60/
subscript gradient
process bigger_stripes/position_101.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_101.80/
subscript gradient
process bigger_stripes/position_101.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_102.00/
subscript gradient
process bigger_stripes/position_102.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_102.20/
subscript gradient
process bigger_stripes/position_102.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_102.40/
subscript gradient
process bigger_stripes/position_102.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_102.60/
subscript gradient
process bigger_stripes/position_102.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_102.80/
subscript gradient
process bigger_stripes/position_102.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_103.00/
subscript gradient
process bigger_stripes/position_103.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_103.20/
subscript gradient
process bigger_stripes/position_103.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_103.40/
subscript gradient
process bigger_stripes/position_103.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_103.60/
subscript gradient
process bigger_stripes/position_103.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_103.80/
subscript gradient
process bigger_stripes/position_103.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_104.00/
subscript gradient
process bigger_stripes/position_104.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_104.20/
subscript gradient
process bigger_stripes/position_104.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_104.40/
subscript gradient
process bigger_stripes/position_104.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_104.60/
subscript gradient
process bigger_stripes/position_104.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_104.80/
subscript gradient
process bigger_stripes/position_104.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_105.00/
subscript gradient
process bigger_stripes/position_105.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_105.20/
subscript gradient
process bigger_stripes/position_105.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_105.40/
subscript gradient
process bigger_stripes/position_105.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_105.60/
subscript gradient
process bigger_stripes/position_105.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_105.80/
subscript gradient
process bigger_stripes/position_105.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_106.00/
subscript gradient
process bigger_stripes/position_106.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_106.20/
subscript gradient
process bigger_stripes/position_106.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_106.40/
subscript gradient
process bigger_stripes/position_106.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_106.60/
subscript gradient
process bigger_stripes/position_106.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_106.80/
subscript gradient
process bigger_stripes/position_106.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_107.00/
subscript gradient
process bigger_stripes/position_107.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_107.20/
subscript gradient
process bigger_stripes/position_107.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_107.40/
subscript gradient
process bigger_stripes/position_107.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_107.60/
subscript gradient
process bigger_stripes/position_107.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_107.80/
subscript gradient
process bigger_stripes/position_107.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_108.00/
subscript gradient
process bigger_stripes/position_108.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_108.20/
subscript gradient
process bigger_stripes/position_108.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_108.40/
subscript gradient
process bigger_stripes/position_108.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_108.60/
subscript gradient
process bigger_stripes/position_108.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_108.80/
subscript gradient
process bigger_stripes/position_108.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_109.00/
subscript gradient
process bigger_stripes/position_109.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_109.20/
subscript gradient
process bigger_stripes/position_109.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_109.40/
subscript gradient
process bigger_stripes/position_109.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_109.60/
subscript gradient
process bigger_stripes/position_109.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_109.80/
subscript gradient
process bigger_stripes/position_109.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_110.00/
subscript gradient
process bigger_stripes/position_110.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_110.20/
subscript gradient
process bigger_stripes/position_110.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_110.40/
subscript gradient
process bigger_stripes/position_110.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_110.60/
subscript gradient
process bigger_stripes/position_110.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_110.80/
subscript gradient
process bigger_stripes/position_110.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_111.00/
subscript gradient
process bigger_stripes/position_111.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_111.20/
subscript gradient
process bigger_stripes/position_111.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_111.40/
subscript gradient
process bigger_stripes/position_111.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_111.60/
subscript gradient
process bigger_stripes/position_111.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_111.80/
subscript gradient
process bigger_stripes/position_111.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_112.00/
subscript gradient
process bigger_stripes/position_112.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_112.20/
subscript gradient
process bigger_stripes/position_112.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_112.40/
subscript gradient
process bigger_stripes/position_112.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_112.60/
subscript gradient
process bigger_stripes/position_112.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_112.80/
subscript gradient
process bigger_stripes/position_112.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_113.00/
subscript gradient
process bigger_stripes/position_113.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_113.20/
subscript gradient
process bigger_stripes/position_113.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_113.40/
subscript gradient
process bigger_stripes/position_113.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_113.60/
subscript gradient
process bigger_stripes/position_113.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_113.80/
subscript gradient
process bigger_stripes/position_113.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_114.00/
subscript gradient
process bigger_stripes/position_114.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_114.20/
subscript gradient
process bigger_stripes/position_114.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_114.40/
subscript gradient
process bigger_stripes/position_114.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_114.60/
subscript gradient
process bigger_stripes/position_114.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_114.80/
subscript gradient
process bigger_stripes/position_114.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_115.00/
subscript gradient
process bigger_stripes/position_115.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_115.20/
subscript gradient
process bigger_stripes/position_115.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_115.40/
subscript gradient
process bigger_stripes/position_115.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_115.60/
subscript gradient
process bigger_stripes/position_115.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_115.80/
subscript gradient
process bigger_stripes/position_115.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_116.00/
subscript gradient
process bigger_stripes/position_116.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_116.20/
subscript gradient
process bigger_stripes/position_116.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_116.40/
subscript gradient
process bigger_stripes/position_116.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_116.60/
subscript gradient
process bigger_stripes/position_116.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_116.80/
subscript gradient
process bigger_stripes/position_116.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_117.00/
subscript gradient
process bigger_stripes/position_117.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_117.20/
subscript gradient
process bigger_stripes/position_117.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_117.40/
subscript gradient
process bigger_stripes/position_117.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_117.60/
subscript gradient
process bigger_stripes/position_117.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_117.80/
subscript gradient
process bigger_stripes/position_117.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_118.00/
subscript gradient
process bigger_stripes/position_118.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_118.20/
subscript gradient
process bigger_stripes/position_118.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_118.40/
subscript gradient
process bigger_stripes/position_118.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_118.60/
subscript gradient
process bigger_stripes/position_118.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_118.80/
subscript gradient
process bigger_stripes/position_118.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_119.00/
subscript gradient
process bigger_stripes/position_119.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_119.20/
subscript gradient
process bigger_stripes/position_119.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_119.40/
subscript gradient
process bigger_stripes/position_119.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_119.60/
subscript gradient
process bigger_stripes/position_119.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_119.80/
subscript gradient
process bigger_stripes/position_119.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_120.00/
subscript gradient
process bigger_stripes/position_120.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_120.20/
subscript gradient
process bigger_stripes/position_120.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_120.40/
subscript gradient
process bigger_stripes/position_120.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_120.60/
subscript gradient
process bigger_stripes/position_120.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_120.80/
subscript gradient
process bigger_stripes/position_120.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_121.00/
subscript gradient
process bigger_stripes/position_121.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_121.20/
subscript gradient
process bigger_stripes/position_121.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_121.40/
subscript gradient
process bigger_stripes/position_121.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_121.60/
subscript gradient
process bigger_stripes/position_121.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_121.80/
subscript gradient
process bigger_stripes/position_121.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_122.00/
subscript gradient
process bigger_stripes/position_122.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_122.20/
subscript gradient
process bigger_stripes/position_122.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_122.40/
subscript gradient
process bigger_stripes/position_122.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_122.60/
subscript gradient
process bigger_stripes/position_122.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_122.80/
subscript gradient
process bigger_stripes/position_122.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_123.00/
subscript gradient
process bigger_stripes/position_123.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_123.20/
subscript gradient
process bigger_stripes/position_123.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_123.40/
subscript gradient
process bigger_stripes/position_123.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_123.60/
subscript gradient
process bigger_stripes/position_123.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_123.80/
subscript gradient
process bigger_stripes/position_123.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_124.00/
subscript gradient
process bigger_stripes/position_124.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_124.20/
subscript gradient
process bigger_stripes/position_124.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_124.40/
subscript gradient
process bigger_stripes/position_124.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_124.60/
subscript gradient
process bigger_stripes/position_124.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_124.80/
subscript gradient
process bigger_stripes/position_124.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_125.00/
subscript gradient
process bigger_stripes/position_125.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_125.20/
subscript gradient
process bigger_stripes/position_125.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_125.40/
subscript gradient
process bigger_stripes/position_125.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_125.60/
subscript gradient
process bigger_stripes/position_125.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_125.80/
subscript gradient
process bigger_stripes/position_125.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_126.00/
subscript gradient
process bigger_stripes/position_126.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_126.20/
subscript gradient
process bigger_stripes/position_126.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_126.40/
subscript gradient
process bigger_stripes/position_126.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_126.60/
subscript gradient
process bigger_stripes/position_126.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_126.80/
subscript gradient
process bigger_stripes/position_126.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_127.00/
subscript gradient
process bigger_stripes/position_127.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_127.20/
subscript gradient
process bigger_stripes/position_127.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_127.40/
subscript gradient
process bigger_stripes/position_127.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_127.60/
subscript gradient
process bigger_stripes/position_127.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_127.80/
subscript gradient
process bigger_stripes/position_127.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_128.00/
subscript gradient
process bigger_stripes/position_128.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_128.20/
subscript gradient
process bigger_stripes/position_128.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_128.40/
subscript gradient
process bigger_stripes/position_128.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_128.60/
subscript gradient
process bigger_stripes/position_128.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_128.80/
subscript gradient
process bigger_stripes/position_128.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_129.00/
subscript gradient
process bigger_stripes/position_129.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_129.20/
subscript gradient
process bigger_stripes/position_129.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_129.40/
subscript gradient
process bigger_stripes/position_129.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_129.60/
subscript gradient
process bigger_stripes/position_129.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_129.80/
subscript gradient
process bigger_stripes/position_129.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_130.00/
subscript gradient
process bigger_stripes/position_130.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_130.20/
subscript gradient
process bigger_stripes/position_130.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_130.40/
subscript gradient
process bigger_stripes/position_130.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_130.60/
subscript gradient
process bigger_stripes/position_130.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_130.80/
subscript gradient
process bigger_stripes/position_130.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_131.00/
subscript gradient
process bigger_stripes/position_131.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_131.20/
subscript gradient
process bigger_stripes/position_131.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_131.40/
subscript gradient
process bigger_stripes/position_131.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_131.60/
subscript gradient
process bigger_stripes/position_131.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_131.80/
subscript gradient
process bigger_stripes/position_131.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_132.00/
subscript gradient
process bigger_stripes/position_132.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_132.20/
subscript gradient
process bigger_stripes/position_132.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_132.40/
subscript gradient
process bigger_stripes/position_132.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_132.60/
subscript gradient
process bigger_stripes/position_132.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_132.80/
subscript gradient
process bigger_stripes/position_132.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_133.00/
subscript gradient
process bigger_stripes/position_133.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_133.20/
subscript gradient
process bigger_stripes/position_133.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_133.40/
subscript gradient
process bigger_stripes/position_133.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_133.60/
subscript gradient
process bigger_stripes/position_133.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_133.80/
subscript gradient
process bigger_stripes/position_133.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_134.00/
subscript gradient
process bigger_stripes/position_134.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_134.20/
subscript gradient
process bigger_stripes/position_134.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_134.40/
subscript gradient
process bigger_stripes/position_134.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_134.60/
subscript gradient
process bigger_stripes/position_134.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_134.80/
subscript gradient
process bigger_stripes/position_134.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_135.00/
subscript gradient
process bigger_stripes/position_135.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_135.20/
subscript gradient
process bigger_stripes/position_135.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_135.40/
subscript gradient
process bigger_stripes/position_135.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_135.60/
subscript gradient
process bigger_stripes/position_135.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_135.80/
subscript gradient
process bigger_stripes/position_135.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_136.00/
subscript gradient
process bigger_stripes/position_136.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_136.20/
subscript gradient
process bigger_stripes/position_136.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_136.40/
subscript gradient
process bigger_stripes/position_136.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_136.60/
subscript gradient
process bigger_stripes/position_136.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_136.80/
subscript gradient
process bigger_stripes/position_136.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_137.00/
subscript gradient
process bigger_stripes/position_137.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_137.20/
subscript gradient
process bigger_stripes/position_137.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_137.40/
subscript gradient
process bigger_stripes/position_137.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_137.60/
subscript gradient
process bigger_stripes/position_137.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_137.80/
subscript gradient
process bigger_stripes/position_137.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_138.00/
subscript gradient
process bigger_stripes/position_138.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_138.20/
subscript gradient
process bigger_stripes/position_138.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_138.40/
subscript gradient
process bigger_stripes/position_138.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_138.60/
subscript gradient
process bigger_stripes/position_138.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_138.80/
subscript gradient
process bigger_stripes/position_138.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_139.00/
subscript gradient
process bigger_stripes/position_139.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_139.20/
subscript gradient
process bigger_stripes/position_139.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_139.40/
subscript gradient
process bigger_stripes/position_139.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_139.60/
subscript gradient
process bigger_stripes/position_139.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_139.80/
subscript gradient
process bigger_stripes/position_139.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_140.00/
subscript gradient
process bigger_stripes/position_140.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_140.20/
subscript gradient
process bigger_stripes/position_140.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_140.40/
subscript gradient
process bigger_stripes/position_140.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_140.60/
subscript gradient
process bigger_stripes/position_140.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_140.80/
subscript gradient
process bigger_stripes/position_140.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_141.00/
subscript gradient
process bigger_stripes/position_141.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_141.20/
subscript gradient
process bigger_stripes/position_141.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_141.40/
subscript gradient
process bigger_stripes/position_141.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_141.60/
subscript gradient
process bigger_stripes/position_141.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_141.80/
subscript gradient
process bigger_stripes/position_141.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_142.00/
subscript gradient
process bigger_stripes/position_142.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_142.20/
subscript gradient
process bigger_stripes/position_142.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_142.40/
subscript gradient
process bigger_stripes/position_142.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_142.60/
subscript gradient
process bigger_stripes/position_142.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_142.80/
subscript gradient
process bigger_stripes/position_142.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_143.00/
subscript gradient
process bigger_stripes/position_143.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_143.20/
subscript gradient
process bigger_stripes/position_143.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_143.40/
subscript gradient
process bigger_stripes/position_143.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_143.60/
subscript gradient
process bigger_stripes/position_143.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_143.80/
subscript gradient
process bigger_stripes/position_143.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_144.00/
subscript gradient
process bigger_stripes/position_144.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_144.20/
subscript gradient
process bigger_stripes/position_144.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_144.40/
subscript gradient
process bigger_stripes/position_144.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_144.60/
subscript gradient
process bigger_stripes/position_144.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_144.80/
subscript gradient
process bigger_stripes/position_144.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_145.00/
subscript gradient
process bigger_stripes/position_145.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_145.20/
subscript gradient
process bigger_stripes/position_145.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_145.40/
subscript gradient
process bigger_stripes/position_145.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_145.60/
subscript gradient
process bigger_stripes/position_145.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_145.80/
subscript gradient
process bigger_stripes/position_145.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_146.00/
subscript gradient
process bigger_stripes/position_146.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_146.20/
subscript gradient
process bigger_stripes/position_146.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_146.40/
subscript gradient
process bigger_stripes/position_146.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_146.60/
subscript gradient
process bigger_stripes/position_146.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_146.80/
subscript gradient
process bigger_stripes/position_146.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_147.00/
subscript gradient
process bigger_stripes/position_147.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_147.20/
subscript gradient
process bigger_stripes/position_147.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_147.40/
subscript gradient
process bigger_stripes/position_147.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_147.60/
subscript gradient
process bigger_stripes/position_147.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_147.80/
subscript gradient
process bigger_stripes/position_147.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_148.00/
subscript gradient
process bigger_stripes/position_148.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_148.20/
subscript gradient
process bigger_stripes/position_148.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_148.40/
subscript gradient
process bigger_stripes/position_148.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_148.60/
subscript gradient
process bigger_stripes/position_148.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_148.80/
subscript gradient
process bigger_stripes/position_148.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_149.00/
subscript gradient
process bigger_stripes/position_149.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_149.20/
subscript gradient
process bigger_stripes/position_149.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_149.40/
subscript gradient
process bigger_stripes/position_149.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_149.60/
subscript gradient
process bigger_stripes/position_149.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_149.80/
subscript gradient
process bigger_stripes/position_149.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_150.00/
subscript gradient
process bigger_stripes/position_150.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_150.20/
subscript gradient
process bigger_stripes/position_150.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_150.40/
subscript gradient
process bigger_stripes/position_150.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_150.60/
subscript gradient
process bigger_stripes/position_150.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_150.80/
subscript gradient
process bigger_stripes/position_150.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_151.00/
subscript gradient
process bigger_stripes/position_151.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_151.20/
subscript gradient
process bigger_stripes/position_151.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_151.40/
subscript gradient
process bigger_stripes/position_151.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_151.60/
subscript gradient
process bigger_stripes/position_151.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_151.80/
subscript gradient
process bigger_stripes/position_151.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_152.00/
subscript gradient
process bigger_stripes/position_152.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_152.20/
subscript gradient
process bigger_stripes/position_152.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_152.40/
subscript gradient
process bigger_stripes/position_152.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_152.60/
subscript gradient
process bigger_stripes/position_152.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_152.80/
subscript gradient
process bigger_stripes/position_152.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_153.00/
subscript gradient
process bigger_stripes/position_153.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_153.20/
subscript gradient
process bigger_stripes/position_153.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_153.40/
subscript gradient
process bigger_stripes/position_153.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_153.60/
subscript gradient
process bigger_stripes/position_153.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_153.80/
subscript gradient
process bigger_stripes/position_153.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_154.00/
subscript gradient
process bigger_stripes/position_154.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_154.20/
subscript gradient
process bigger_stripes/position_154.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_154.40/
subscript gradient
process bigger_stripes/position_154.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_154.60/
subscript gradient
process bigger_stripes/position_154.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_154.80/
subscript gradient
process bigger_stripes/position_154.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_155.00/
subscript gradient
process bigger_stripes/position_155.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_155.20/
subscript gradient
process bigger_stripes/position_155.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_155.40/
subscript gradient
process bigger_stripes/position_155.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_155.60/
subscript gradient
process bigger_stripes/position_155.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_155.80/
subscript gradient
process bigger_stripes/position_155.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_156.00/
subscript gradient
process bigger_stripes/position_156.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_156.20/
subscript gradient
process bigger_stripes/position_156.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_156.40/
subscript gradient
process bigger_stripes/position_156.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_156.60/
subscript gradient
process bigger_stripes/position_156.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_156.80/
subscript gradient
process bigger_stripes/position_156.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_157.00/
subscript gradient
process bigger_stripes/position_157.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_157.20/
subscript gradient
process bigger_stripes/position_157.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_157.40/
subscript gradient
process bigger_stripes/position_157.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_157.60/
subscript gradient
process bigger_stripes/position_157.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_157.80/
subscript gradient
process bigger_stripes/position_157.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_158.00/
subscript gradient
process bigger_stripes/position_158.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_158.20/
subscript gradient
process bigger_stripes/position_158.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_158.40/
subscript gradient
process bigger_stripes/position_158.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_158.60/
subscript gradient
process bigger_stripes/position_158.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_158.80/
subscript gradient
process bigger_stripes/position_158.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_159.00/
subscript gradient
process bigger_stripes/position_159.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_159.20/
subscript gradient
process bigger_stripes/position_159.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_159.40/
subscript gradient
process bigger_stripes/position_159.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_159.60/
subscript gradient
process bigger_stripes/position_159.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_159.80/
subscript gradient
process bigger_stripes/position_159.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_160.00/
subscript gradient
process bigger_stripes/position_160.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_160.20/
subscript gradient
process bigger_stripes/position_160.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_160.40/
subscript gradient
process bigger_stripes/position_160.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_160.60/
subscript gradient
process bigger_stripes/position_160.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_160.80/
subscript gradient
process bigger_stripes/position_160.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_161.00/
subscript gradient
process bigger_stripes/position_161.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_161.20/
subscript gradient
process bigger_stripes/position_161.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_161.40/
subscript gradient
process bigger_stripes/position_161.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_161.60/
subscript gradient
process bigger_stripes/position_161.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_161.80/
subscript gradient
process bigger_stripes/position_161.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_162.00/
subscript gradient
process bigger_stripes/position_162.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_162.20/
subscript gradient
process bigger_stripes/position_162.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_162.40/
subscript gradient
process bigger_stripes/position_162.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_162.60/
subscript gradient
process bigger_stripes/position_162.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_162.80/
subscript gradient
process bigger_stripes/position_162.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_163.00/
subscript gradient
process bigger_stripes/position_163.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_163.20/
subscript gradient
process bigger_stripes/position_163.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_163.40/
subscript gradient
process bigger_stripes/position_163.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_163.60/
subscript gradient
process bigger_stripes/position_163.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_163.80/
subscript gradient
process bigger_stripes/position_163.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_164.00/
subscript gradient
process bigger_stripes/position_164.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_164.20/
subscript gradient
process bigger_stripes/position_164.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_164.40/
subscript gradient
process bigger_stripes/position_164.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_164.60/
subscript gradient
process bigger_stripes/position_164.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_164.80/
subscript gradient
process bigger_stripes/position_164.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_165.00/
subscript gradient
process bigger_stripes/position_165.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_165.20/
subscript gradient
process bigger_stripes/position_165.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_165.40/
subscript gradient
process bigger_stripes/position_165.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_165.60/
subscript gradient
process bigger_stripes/position_165.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_165.80/
subscript gradient
process bigger_stripes/position_165.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_166.00/
subscript gradient
process bigger_stripes/position_166.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_166.20/
subscript gradient
process bigger_stripes/position_166.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_166.40/
subscript gradient
process bigger_stripes/position_166.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_166.60/
subscript gradient
process bigger_stripes/position_166.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_166.80/
subscript gradient
process bigger_stripes/position_166.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_167.00/
subscript gradient
process bigger_stripes/position_167.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_167.20/
subscript gradient
process bigger_stripes/position_167.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_167.40/
subscript gradient
process bigger_stripes/position_167.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_167.60/
subscript gradient
process bigger_stripes/position_167.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_167.80/
subscript gradient
process bigger_stripes/position_167.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_168.00/
subscript gradient
process bigger_stripes/position_168.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_168.20/
subscript gradient
process bigger_stripes/position_168.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_168.40/
subscript gradient
process bigger_stripes/position_168.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_168.60/
subscript gradient
process bigger_stripes/position_168.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_168.80/
subscript gradient
process bigger_stripes/position_168.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_169.00/
subscript gradient
process bigger_stripes/position_169.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_169.20/
subscript gradient
process bigger_stripes/position_169.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_169.40/
subscript gradient
process bigger_stripes/position_169.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_169.60/
subscript gradient
process bigger_stripes/position_169.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_169.80/
subscript gradient
process bigger_stripes/position_169.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_170.00/
subscript gradient
process bigger_stripes/position_170.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_170.20/
subscript gradient
process bigger_stripes/position_170.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_170.40/
subscript gradient
process bigger_stripes/position_170.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_170.60/
subscript gradient
process bigger_stripes/position_170.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_170.80/
subscript gradient
process bigger_stripes/position_170.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_171.00/
subscript gradient
process bigger_stripes/position_171.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_171.20/
subscript gradient
process bigger_stripes/position_171.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_171.40/
subscript gradient
process bigger_stripes/position_171.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_171.60/
subscript gradient
process bigger_stripes/position_171.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_171.80/
subscript gradient
process bigger_stripes/position_171.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_172.00/
subscript gradient
process bigger_stripes/position_172.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_172.20/
subscript gradient
process bigger_stripes/position_172.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_172.40/
subscript gradient
process bigger_stripes/position_172.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_172.60/
subscript gradient
process bigger_stripes/position_172.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_172.80/
subscript gradient
process bigger_stripes/position_172.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_173.00/
subscript gradient
process bigger_stripes/position_173.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_173.20/
subscript gradient
process bigger_stripes/position_173.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_173.40/
subscript gradient
process bigger_stripes/position_173.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_173.60/
subscript gradient
process bigger_stripes/position_173.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_173.80/
subscript gradient
process bigger_stripes/position_173.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_174.00/
subscript gradient
process bigger_stripes/position_174.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_174.20/
subscript gradient
process bigger_stripes/position_174.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_174.40/
subscript gradient
process bigger_stripes/position_174.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_174.60/
subscript gradient
process bigger_stripes/position_174.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_174.80/
subscript gradient
process bigger_stripes/position_174.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_175.00/
subscript gradient
process bigger_stripes/position_175.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_175.20/
subscript gradient
process bigger_stripes/position_175.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_175.40/
subscript gradient
process bigger_stripes/position_175.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_175.60/
subscript gradient
process bigger_stripes/position_175.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_175.80/
subscript gradient
process bigger_stripes/position_175.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_176.00/
subscript gradient
process bigger_stripes/position_176.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_176.20/
subscript gradient
process bigger_stripes/position_176.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_176.40/
subscript gradient
process bigger_stripes/position_176.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_176.60/
subscript gradient
process bigger_stripes/position_176.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_176.80/
subscript gradient
process bigger_stripes/position_176.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_177.00/
subscript gradient
process bigger_stripes/position_177.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_177.20/
subscript gradient
process bigger_stripes/position_177.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_177.40/
subscript gradient
process bigger_stripes/position_177.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_177.60/
subscript gradient
process bigger_stripes/position_177.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_177.80/
subscript gradient
process bigger_stripes/position_177.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_178.00/
subscript gradient
process bigger_stripes/position_178.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_178.20/
subscript gradient
process bigger_stripes/position_178.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_178.40/
subscript gradient
process bigger_stripes/position_178.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_178.60/
subscript gradient
process bigger_stripes/position_178.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_178.80/
subscript gradient
process bigger_stripes/position_178.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_179.00/
subscript gradient
process bigger_stripes/position_179.00/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_179.20/
subscript gradient
process bigger_stripes/position_179.20/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_179.40/
subscript gradient
process bigger_stripes/position_179.40/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_179.60/
subscript gradient
process bigger_stripes/position_179.60/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_179.80/
subscript gradient
process bigger_stripes/position_179.80/
status
move 0.20
delay 2.000
prefix bigger_stripes/position_180.00/
subscript gradient
process bigger_stripes/position_180.00/
status
