prefix calib_color_dots/
home
color 0
hdr blank_0
color 255
hdr white_0
dots
hdr dots_0
move 5
delay 2.000000
color 0
hdr blank_1
color 255
hdr white_1
dots
hdr dots_1
move 5
delay 2.000000
color 0
hdr blank_2
color 255
hdr white_2
dots
hdr dots_2
move 5
delay 2.000000
color 0
hdr blank_3
color 255
hdr white_3
dots
hdr dots_3
move 5
delay 2.000000
color 0
hdr blank_4
color 255
hdr white_4
dots
hdr dots_4
move 5
delay 2.000000
color 0
hdr blank_5
color 255
hdr white_5
dots
hdr dots_5
move 5
delay 2.000000
color 0
hdr blank_6
color 255
hdr white_6
dots
hdr dots_6
move 5
delay 2.000000
color 0
hdr blank_7
color 255
hdr white_7
dots
hdr dots_7
move 5
delay 2.000000
color 0
hdr blank_8
color 255
hdr white_8
dots
hdr dots_8
move 5
delay 2.000000
color 0
hdr blank_9
color 255
hdr white_9
dots
hdr dots_9
move 5
delay 2.000000
color 0
hdr blank_10
color 255
hdr white_10
dots
hdr dots_10
move 5
delay 2.000000
color 0
hdr blank_11
color 255
hdr white_11
dots
hdr dots_11
move 5
delay 2.000000
color 0
hdr blank_12
color 255
hdr white_12
dots
hdr dots_12
move 5
delay 2.000000
color 0
hdr blank_13
color 255
hdr white_13
dots
hdr dots_13
move 5
delay 2.000000
color 0
hdr blank_14
color 255
hdr white_14
dots
hdr dots_14
move 5
delay 2.000000
color 0
hdr blank_15
color 255
hdr white_15
dots
hdr dots_15
move 5
delay 2.000000
color 0
hdr blank_16
color 255
hdr white_16
dots
hdr dots_16
move 5
delay 2.000000
color 0
hdr blank_17
color 255
hdr white_17
dots
hdr dots_17
move 5
delay 2.000000
color 0
hdr blank_18
color 255
hdr white_18
dots
hdr dots_18
move 5
delay 2.000000
color 0
hdr blank_19
color 255
hdr white_19
dots
hdr dots_19
move 5
delay 2.000000
color 0
hdr blank_20
color 255
hdr white_20
dots
hdr dots_20
move 5
delay 2.000000
color 0
hdr blank_21
color 255
hdr white_21
dots
hdr dots_21
move 5
delay 2.000000
color 0
hdr blank_22
color 255
hdr white_22
dots
hdr dots_22
move 5
delay 2.000000
color 0
hdr blank_23
color 255
hdr white_23
dots
hdr dots_23
move 5
delay 2.000000
color 0
hdr blank_24
color 255
hdr white_24
dots
hdr dots_24
move 5
delay 2.000000
color 0
hdr blank_25
color 255
hdr white_25
dots
hdr dots_25
move 5
delay 2.000000
color 0
hdr blank_26
color 255
hdr white_26
dots
hdr dots_26
move 5
delay 2.000000
color 0
hdr blank_27
color 255
hdr white_27
dots
hdr dots_27
move 5
delay 2.000000
color 0
hdr blank_28
color 255
hdr white_28
dots
hdr dots_28
move 5
delay 2.000000
color 0
hdr blank_29
color 255
hdr white_29
dots
hdr dots_29
move 5
delay 2.000000
color 0
hdr blank_30
color 255
hdr white_30
dots
hdr dots_30
move 5
delay 2.000000
color 0
hdr blank_31
color 255
hdr white_31
dots
hdr dots_31
move 5
delay 2.000000
color 0
hdr blank_32
color 255
hdr white_32
dots
hdr dots_32
move 5
delay 2.000000
color 0
hdr blank_33
color 255
hdr white_33
dots
hdr dots_33
move 5
delay 2.000000
color 0
hdr blank_34
color 255
hdr white_34
dots
hdr dots_34
move 5
delay 2.000000
color 0
hdr blank_35
color 255
hdr white_35
dots
hdr dots_35
move 5
delay 2.000000
color 0
hdr blank_36
color 255
hdr white_36
dots
hdr dots_36
move 5
delay 2.000000
color 0
hdr blank_37
color 255
hdr white_37
dots
hdr dots_37
move 5
delay 2.000000
color 0
hdr blank_38
color 255
hdr white_38
dots
hdr dots_38
move 5
delay 2.000000
color 0
hdr blank_39
color 255
hdr white_39
dots
hdr dots_39
move 5
delay 2.000000
color 0
hdr blank_40
color 255
hdr white_40
dots
hdr dots_40
move 5
delay 2.000000
color 0
hdr blank_41
color 255
hdr white_41
dots
hdr dots_41
move 5
delay 2.000000
color 0
hdr blank_42
color 255
hdr white_42
dots
hdr dots_42
move 5
delay 2.000000
color 0
hdr blank_43
color 255
hdr white_43
dots
hdr dots_43
move 5
delay 2.000000
color 0
hdr blank_44
color 255
hdr white_44
dots
hdr dots_44
move 5
delay 2.000000
color 0
hdr blank_45
color 255
hdr white_45
dots
hdr dots_45
move 5
delay 2.000000
color 0
hdr blank_46
color 255
hdr white_46
dots
hdr dots_46
move 5
delay 2.000000
color 0
hdr blank_47
color 255
hdr white_47
dots
hdr dots_47
move 5
delay 2.000000
color 0
hdr blank_48
color 255
hdr white_48
dots
hdr dots_48
move 5
delay 2.000000
color 0
hdr blank_49
color 255
hdr white_49
dots
hdr dots_49
move 5
delay 2.000000
color 0
hdr blank_50
color 255
hdr white_50
dots
hdr dots_50
move 5
delay 2.000000
color 0
hdr blank_51
color 255
hdr white_51
dots
hdr dots_51
move 5
delay 2.000000
color 0
hdr blank_52
color 255
hdr white_52
dots
hdr dots_52
move 5
delay 2.000000
color 0
hdr blank_53
color 255
hdr white_53
dots
hdr dots_53
move 5
delay 2.000000
color 0
hdr blank_54
color 255
hdr white_54
dots
hdr dots_54
move 5
delay 2.000000
color 0
hdr blank_55
color 255
hdr white_55
dots
hdr dots_55
move 5
delay 2.000000
color 0
hdr blank_56
color 255
hdr white_56
dots
hdr dots_56
move 5
delay 2.000000
color 0
hdr blank_57
color 255
hdr white_57
dots
hdr dots_57
move 5
delay 2.000000
color 0
hdr blank_58
color 255
hdr white_58
dots
hdr dots_58
move 5
delay 2.000000
color 0
hdr blank_59
color 255
hdr white_59
dots
hdr dots_59
move 5
delay 2.000000
color 0
hdr blank_60
color 255
hdr white_60
dots
hdr dots_60
move 5
delay 2.000000
color 0
hdr blank_61
color 255
hdr white_61
dots
hdr dots_61
move 5
delay 2.000000
color 0
hdr blank_62
color 255
hdr white_62
dots
hdr dots_62
move 5
delay 2.000000
color 0
hdr blank_63
color 255
hdr white_63
dots
hdr dots_63
move 5
delay 2.000000
color 0
hdr blank_64
color 255
hdr white_64
dots
hdr dots_64
status
