prefix calib/
home
color 0
hdr blank_0
color 255
hdr white_0
checker
hdr checker_0
move 5
delay 2.000000
color 0
hdr blank_1
color 255
hdr white_1
checker
hdr checker_1
move 5
delay 2.000000
color 0
hdr blank_2
color 255
hdr white_2
checker
hdr checker_2
move 5
delay 2.000000
color 0
hdr blank_3
color 255
hdr white_3
checker
hdr checker_3
move 5
delay 2.000000
color 0
hdr blank_4
color 255
hdr white_4
checker
hdr checker_4
move 5
delay 2.000000
color 0
hdr blank_5
color 255
hdr white_5
checker
hdr checker_5
move 5
delay 2.000000
color 0
hdr blank_6
color 255
hdr white_6
checker
hdr checker_6
move 5
delay 2.000000
color 0
hdr blank_7
color 255
hdr white_7
checker
hdr checker_7
move 5
delay 2.000000
color 0
hdr blank_8
color 255
hdr white_8
checker
hdr checker_8
move 5
delay 2.000000
color 0
hdr blank_9
color 255
hdr white_9
checker
hdr checker_9
move 5
delay 2.000000
color 0
hdr blank_10
color 255
hdr white_10
checker
hdr checker_10
move 5
delay 2.000000
color 0
hdr blank_11
color 255
hdr white_11
checker
hdr checker_11
move 5
delay 2.000000
color 0
hdr blank_12
color 255
hdr white_12
checker
hdr checker_12
move 5
delay 2.000000
color 0
hdr blank_13
color 255
hdr white_13
checker
hdr checker_13
move 5
delay 2.000000
color 0
hdr blank_14
color 255
hdr white_14
checker
hdr checker_14
move 5
delay 2.000000
color 0
hdr blank_15
color 255
hdr white_15
checker
hdr checker_15
move 5
delay 2.000000
color 0
hdr blank_16
color 255
hdr white_16
checker
hdr checker_16
move 5
delay 2.000000
color 0
hdr blank_17
color 255
hdr white_17
checker
hdr checker_17
move 5
delay 2.000000
color 0
hdr blank_18
color 255
hdr white_18
checker
hdr checker_18
move 5
delay 2.000000
color 0
hdr blank_19
color 255
hdr white_19
checker
hdr checker_19
move 5
delay 2.000000
color 0
hdr blank_20
color 255
hdr white_20
checker
hdr checker_20
move 5
delay 2.000000
color 0
hdr blank_21
color 255
hdr white_21
checker
hdr checker_21
move 5
delay 2.000000
color 0
hdr blank_22
color 255
hdr white_22
checker
hdr checker_22
move 5
delay 2.000000
color 0
hdr blank_23
color 255
hdr white_23
checker
hdr checker_23
move 5
delay 2.000000
color 0
hdr blank_24
color 255
hdr white_24
checker
hdr checker_24
move 5
delay 2.000000
color 0
hdr blank_25
color 255
hdr white_25
checker
hdr checker_25
move 5
delay 2.000000
color 0
hdr blank_26
color 255
hdr white_26
checker
hdr checker_26
move 5
delay 2.000000
color 0
hdr blank_27
color 255
hdr white_27
checker
hdr checker_27
move 5
delay 2.000000
color 0
hdr blank_28
color 255
hdr white_28
checker
hdr checker_28
move 5
delay 2.000000
color 0
hdr blank_29
color 255
hdr white_29
checker
hdr checker_29
move 5
delay 2.000000
color 0
hdr blank_30
color 255
hdr white_30
checker
hdr checker_30
move 5
delay 2.000000
color 0
hdr blank_31
color 255
hdr white_31
checker
hdr checker_31
move 5
delay 2.000000
color 0
hdr blank_32
color 255
hdr white_32
checker
hdr checker_32
move 5
delay 2.000000
color 0
hdr blank_33
color 255
hdr white_33
checker
hdr checker_33
move 5
delay 2.000000
color 0
hdr blank_34
color 255
hdr white_34
checker
hdr checker_34
move 5
delay 2.000000
color 0
hdr blank_35
color 255
hdr white_35
checker
hdr checker_35
move 5
delay 2.000000
color 0
hdr blank_36
color 255
hdr white_36
checker
hdr checker_36
move 5
delay 2.000000
color 0
hdr blank_37
color 255
hdr white_37
checker
hdr checker_37
move 5
delay 2.000000
color 0
hdr blank_38
color 255
hdr white_38
checker
hdr checker_38
move 5
delay 2.000000
color 0
hdr blank_39
color 255
hdr white_39
checker
hdr checker_39
move 5
delay 2.000000
color 0
hdr blank_40
color 255
hdr white_40
checker
hdr checker_40
move 5
delay 2.000000
color 0
hdr blank_41
color 255
hdr white_41
checker
hdr checker_41
move 5
delay 2.000000
color 0
hdr blank_42
color 255
hdr white_42
checker
hdr checker_42
move 5
delay 2.000000
color 0
hdr blank_43
color 255
hdr white_43
checker
hdr checker_43
move 5
delay 2.000000
color 0
hdr blank_44
color 255
hdr white_44
checker
hdr checker_44
move 5
delay 2.000000
color 0
hdr blank_45
color 255
hdr white_45
checker
hdr checker_45
move 5
delay 2.000000
color 0
hdr blank_46
color 255
hdr white_46
checker
hdr checker_46
move 5
delay 2.000000
color 0
hdr blank_47
color 255
hdr white_47
checker
hdr checker_47
move 5
delay 2.000000
color 0
hdr blank_48
color 255
hdr white_48
checker
hdr checker_48
move 5
delay 2.000000
color 0
hdr blank_49
color 255
hdr white_49
checker
hdr checker_49
move 5
delay 2.000000
color 0
hdr blank_50
color 255
hdr white_50
checker
hdr checker_50
move 5
delay 2.000000
color 0
hdr blank_51
color 255
hdr white_51
checker
hdr checker_51
move 5
delay 2.000000
color 0
hdr blank_52
color 255
hdr white_52
checker
hdr checker_52
move 5
delay 2.000000
color 0
hdr blank_53
color 255
hdr white_53
checker
hdr checker_53
move 5
delay 2.000000
color 0
hdr blank_54
color 255
hdr white_54
checker
hdr checker_54
move 5
delay 2.000000
color 0
hdr blank_55
color 255
hdr white_55
checker
hdr checker_55
move 5
delay 2.000000
color 0
hdr blank_56
color 255
hdr white_56
checker
hdr checker_56
move 5
delay 2.000000
color 0
hdr blank_57
color 255
hdr white_57
checker
hdr checker_57
move 5
delay 2.000000
color 0
hdr blank_58
color 255
hdr white_58
checker
hdr checker_58
move 5
delay 2.000000
color 0
hdr blank_59
color 255
hdr white_59
checker
hdr checker_59
move 5
delay 2.000000
color 0
hdr blank_60
color 255
hdr white_60
checker
hdr checker_60
move 5
delay 2.000000
color 0
hdr blank_61
color 255
hdr white_61
checker
hdr checker_61
move 5
delay 2.000000
color 0
hdr blank_62
color 255
hdr white_62
checker
hdr checker_62
move 5
delay 2.000000
color 0
hdr blank_63
color 255
hdr white_63
checker
hdr checker_63
move 5
delay 2.000000
color 0
hdr blank_64
color 255
hdr white_64
checker
hdr checker_64
status
