prefix calib_color/
home
color 0
hdr blank_0
color 255
hdr white_0
checker r d
hdr checker_r_d_0
checker g d
hdr checker_g_d_0
checker b d
hdr checker_b_d_0
move 5
delay 2.000000
color 0
hdr blank_1
color 255
hdr white_1
checker r d
hdr checker_r_d_1
checker g d
hdr checker_g_d_1
checker b d
hdr checker_b_d_1
move 5
delay 2.000000
color 0
hdr blank_2
color 255
hdr white_2
checker r d
hdr checker_r_d_2
checker g d
hdr checker_g_d_2
checker b d
hdr checker_b_d_2
move 5
delay 2.000000
color 0
hdr blank_3
color 255
hdr white_3
checker r d
hdr checker_r_d_3
checker g d
hdr checker_g_d_3
checker b d
hdr checker_b_d_3
move 5
delay 2.000000
color 0
hdr blank_4
color 255
hdr white_4
checker r d
hdr checker_r_d_4
checker g d
hdr checker_g_d_4
checker b d
hdr checker_b_d_4
move 5
delay 2.000000
color 0
hdr blank_5
color 255
hdr white_5
checker r d
hdr checker_r_d_5
checker g d
hdr checker_g_d_5
checker b d
hdr checker_b_d_5
move 5
delay 2.000000
color 0
hdr blank_6
color 255
hdr white_6
checker r d
hdr checker_r_d_6
checker g d
hdr checker_g_d_6
checker b d
hdr checker_b_d_6
move 5
delay 2.000000
color 0
hdr blank_7
color 255
hdr white_7
checker r d
hdr checker_r_d_7
checker g d
hdr checker_g_d_7
checker b d
hdr checker_b_d_7
move 5
delay 2.000000
color 0
hdr blank_8
color 255
hdr white_8
checker r d
hdr checker_r_d_8
checker g d
hdr checker_g_d_8
checker b d
hdr checker_b_d_8
move 5
delay 2.000000
color 0
hdr blank_9
color 255
hdr white_9
checker r d
hdr checker_r_d_9
checker g d
hdr checker_g_d_9
checker b d
hdr checker_b_d_9
move 5
delay 2.000000
color 0
hdr blank_10
color 255
hdr white_10
checker r d
hdr checker_r_d_10
checker g d
hdr checker_g_d_10
checker b d
hdr checker_b_d_10
move 5
delay 2.000000
color 0
hdr blank_11
color 255
hdr white_11
checker r d
hdr checker_r_d_11
checker g d
hdr checker_g_d_11
checker b d
hdr checker_b_d_11
move 5
delay 2.000000
color 0
hdr blank_12
color 255
hdr white_12
checker r d
hdr checker_r_d_12
checker g d
hdr checker_g_d_12
checker b d
hdr checker_b_d_12
move 5
delay 2.000000
color 0
hdr blank_13
color 255
hdr white_13
checker r d
hdr checker_r_d_13
checker g d
hdr checker_g_d_13
checker b d
hdr checker_b_d_13
move 5
delay 2.000000
color 0
hdr blank_14
color 255
hdr white_14
checker r d
hdr checker_r_d_14
checker g d
hdr checker_g_d_14
checker b d
hdr checker_b_d_14
move 5
delay 2.000000
color 0
hdr blank_15
color 255
hdr white_15
checker r d
hdr checker_r_d_15
checker g d
hdr checker_g_d_15
checker b d
hdr checker_b_d_15
move 5
delay 2.000000
color 0
hdr blank_16
color 255
hdr white_16
checker r d
hdr checker_r_d_16
checker g d
hdr checker_g_d_16
checker b d
hdr checker_b_d_16
move 5
delay 2.000000
color 0
hdr blank_17
color 255
hdr white_17
checker r d
hdr checker_r_d_17
checker g d
hdr checker_g_d_17
checker b d
hdr checker_b_d_17
move 5
delay 2.000000
color 0
hdr blank_18
color 255
hdr white_18
checker r d
hdr checker_r_d_18
checker g d
hdr checker_g_d_18
checker b d
hdr checker_b_d_18
move 5
delay 2.000000
color 0
hdr blank_19
color 255
hdr white_19
checker r d
hdr checker_r_d_19
checker g d
hdr checker_g_d_19
checker b d
hdr checker_b_d_19
move 5
delay 2.000000
color 0
hdr blank_20
color 255
hdr white_20
checker r d
hdr checker_r_d_20
checker g d
hdr checker_g_d_20
checker b d
hdr checker_b_d_20
move 5
delay 2.000000
color 0
hdr blank_21
color 255
hdr white_21
checker r d
hdr checker_r_d_21
checker g d
hdr checker_g_d_21
checker b d
hdr checker_b_d_21
move 5
delay 2.000000
color 0
hdr blank_22
color 255
hdr white_22
checker r d
hdr checker_r_d_22
checker g d
hdr checker_g_d_22
checker b d
hdr checker_b_d_22
move 5
delay 2.000000
color 0
hdr blank_23
color 255
hdr white_23
checker r d
hdr checker_r_d_23
checker g d
hdr checker_g_d_23
checker b d
hdr checker_b_d_23
move 5
delay 2.000000
color 0
hdr blank_24
color 255
hdr white_24
checker r d
hdr checker_r_d_24
checker g d
hdr checker_g_d_24
checker b d
hdr checker_b_d_24
move 5
delay 2.000000
color 0
hdr blank_25
color 255
hdr white_25
checker r d
hdr checker_r_d_25
checker g d
hdr checker_g_d_25
checker b d
hdr checker_b_d_25
move 5
delay 2.000000
color 0
hdr blank_26
color 255
hdr white_26
checker r d
hdr checker_r_d_26
checker g d
hdr checker_g_d_26
checker b d
hdr checker_b_d_26
move 5
delay 2.000000
color 0
hdr blank_27
color 255
hdr white_27
checker r d
hdr checker_r_d_27
checker g d
hdr checker_g_d_27
checker b d
hdr checker_b_d_27
move 5
delay 2.000000
color 0
hdr blank_28
color 255
hdr white_28
checker r d
hdr checker_r_d_28
checker g d
hdr checker_g_d_28
checker b d
hdr checker_b_d_28
move 5
delay 2.000000
color 0
hdr blank_29
color 255
hdr white_29
checker r d
hdr checker_r_d_29
checker g d
hdr checker_g_d_29
checker b d
hdr checker_b_d_29
move 5
delay 2.000000
color 0
hdr blank_30
color 255
hdr white_30
checker r d
hdr checker_r_d_30
checker g d
hdr checker_g_d_30
checker b d
hdr checker_b_d_30
move 5
delay 2.000000
color 0
hdr blank_31
color 255
hdr white_31
checker r d
hdr checker_r_d_31
checker g d
hdr checker_g_d_31
checker b d
hdr checker_b_d_31
move 5
delay 2.000000
color 0
hdr blank_32
color 255
hdr white_32
checker r d
hdr checker_r_d_32
checker g d
hdr checker_g_d_32
checker b d
hdr checker_b_d_32
move 5
delay 2.000000
color 0
hdr blank_33
color 255
hdr white_33
checker r d
hdr checker_r_d_33
checker g d
hdr checker_g_d_33
checker b d
hdr checker_b_d_33
move 5
delay 2.000000
color 0
hdr blank_34
color 255
hdr white_34
checker r d
hdr checker_r_d_34
checker g d
hdr checker_g_d_34
checker b d
hdr checker_b_d_34
move 5
delay 2.000000
color 0
hdr blank_35
color 255
hdr white_35
checker r d
hdr checker_r_d_35
checker g d
hdr checker_g_d_35
checker b d
hdr checker_b_d_35
move 5
delay 2.000000
color 0
hdr blank_36
color 255
hdr white_36
checker r d
hdr checker_r_d_36
checker g d
hdr checker_g_d_36
checker b d
hdr checker_b_d_36
move 5
delay 2.000000
color 0
hdr blank_37
color 255
hdr white_37
checker r d
hdr checker_r_d_37
checker g d
hdr checker_g_d_37
checker b d
hdr checker_b_d_37
move 5
delay 2.000000
color 0
hdr blank_38
color 255
hdr white_38
checker r d
hdr checker_r_d_38
checker g d
hdr checker_g_d_38
checker b d
hdr checker_b_d_38
move 5
delay 2.000000
color 0
hdr blank_39
color 255
hdr white_39
checker r d
hdr checker_r_d_39
checker g d
hdr checker_g_d_39
checker b d
hdr checker_b_d_39
move 5
delay 2.000000
color 0
hdr blank_40
color 255
hdr white_40
checker r d
hdr checker_r_d_40
checker g d
hdr checker_g_d_40
checker b d
hdr checker_b_d_40
move 5
delay 2.000000
color 0
hdr blank_41
color 255
hdr white_41
checker r d
hdr checker_r_d_41
checker g d
hdr checker_g_d_41
checker b d
hdr checker_b_d_41
move 5
delay 2.000000
color 0
hdr blank_42
color 255
hdr white_42
checker r d
hdr checker_r_d_42
checker g d
hdr checker_g_d_42
checker b d
hdr checker_b_d_42
move 5
delay 2.000000
color 0
hdr blank_43
color 255
hdr white_43
checker r d
hdr checker_r_d_43
checker g d
hdr checker_g_d_43
checker b d
hdr checker_b_d_43
move 5
delay 2.000000
color 0
hdr blank_44
color 255
hdr white_44
checker r d
hdr checker_r_d_44
checker g d
hdr checker_g_d_44
checker b d
hdr checker_b_d_44
move 5
delay 2.000000
color 0
hdr blank_45
color 255
hdr white_45
checker r d
hdr checker_r_d_45
checker g d
hdr checker_g_d_45
checker b d
hdr checker_b_d_45
move 5
delay 2.000000
color 0
hdr blank_46
color 255
hdr white_46
checker r d
hdr checker_r_d_46
checker g d
hdr checker_g_d_46
checker b d
hdr checker_b_d_46
move 5
delay 2.000000
color 0
hdr blank_47
color 255
hdr white_47
checker r d
hdr checker_r_d_47
checker g d
hdr checker_g_d_47
checker b d
hdr checker_b_d_47
move 5
delay 2.000000
color 0
hdr blank_48
color 255
hdr white_48
checker r d
hdr checker_r_d_48
checker g d
hdr checker_g_d_48
checker b d
hdr checker_b_d_48
move 5
delay 2.000000
color 0
hdr blank_49
color 255
hdr white_49
checker r d
hdr checker_r_d_49
checker g d
hdr checker_g_d_49
checker b d
hdr checker_b_d_49
move 5
delay 2.000000
color 0
hdr blank_50
color 255
hdr white_50
checker r d
hdr checker_r_d_50
checker g d
hdr checker_g_d_50
checker b d
hdr checker_b_d_50
move 5
delay 2.000000
color 0
hdr blank_51
color 255
hdr white_51
checker r d
hdr checker_r_d_51
checker g d
hdr checker_g_d_51
checker b d
hdr checker_b_d_51
move 5
delay 2.000000
color 0
hdr blank_52
color 255
hdr white_52
checker r d
hdr checker_r_d_52
checker g d
hdr checker_g_d_52
checker b d
hdr checker_b_d_52
move 5
delay 2.000000
color 0
hdr blank_53
color 255
hdr white_53
checker r d
hdr checker_r_d_53
checker g d
hdr checker_g_d_53
checker b d
hdr checker_b_d_53
move 5
delay 2.000000
color 0
hdr blank_54
color 255
hdr white_54
checker r d
hdr checker_r_d_54
checker g d
hdr checker_g_d_54
checker b d
hdr checker_b_d_54
move 5
delay 2.000000
color 0
hdr blank_55
color 255
hdr white_55
checker r d
hdr checker_r_d_55
checker g d
hdr checker_g_d_55
checker b d
hdr checker_b_d_55
move 5
delay 2.000000
color 0
hdr blank_56
color 255
hdr white_56
checker r d
hdr checker_r_d_56
checker g d
hdr checker_g_d_56
checker b d
hdr checker_b_d_56
move 5
delay 2.000000
color 0
hdr blank_57
color 255
hdr white_57
checker r d
hdr checker_r_d_57
checker g d
hdr checker_g_d_57
checker b d
hdr checker_b_d_57
move 5
delay 2.000000
color 0
hdr blank_58
color 255
hdr white_58
checker r d
hdr checker_r_d_58
checker g d
hdr checker_g_d_58
checker b d
hdr checker_b_d_58
move 5
delay 2.000000
color 0
hdr blank_59
color 255
hdr white_59
checker r d
hdr checker_r_d_59
checker g d
hdr checker_g_d_59
checker b d
hdr checker_b_d_59
move 5
delay 2.000000
color 0
hdr blank_60
color 255
hdr white_60
checker r d
hdr checker_r_d_60
checker g d
hdr checker_g_d_60
checker b d
hdr checker_b_d_60
move 5
delay 2.000000
color 0
hdr blank_61
color 255
hdr white_61
checker r d
hdr checker_r_d_61
checker g d
hdr checker_g_d_61
checker b d
hdr checker_b_d_61
move 5
delay 2.000000
color 0
hdr blank_62
color 255
hdr white_62
checker r d
hdr checker_r_d_62
checker g d
hdr checker_g_d_62
checker b d
hdr checker_b_d_62
move 5
delay 2.000000
color 0
hdr blank_63
color 255
hdr white_63
checker r d
hdr checker_r_d_63
checker g d
hdr checker_g_d_63
checker b d
hdr checker_b_d_63
move 5
delay 2.000000
color 0
hdr blank_64
color 255
hdr white_64
checker r d
hdr checker_r_d_64
checker g d
hdr checker_g_d_64
checker b d
hdr checker_b_d_64
status
