prefix mid_stripes/
prefix mid_stripes/position_0.00/
subscript gradient
process mid_stripes/position_0.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_1.00/
subscript gradient
process mid_stripes/position_1.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_2.00/
subscript gradient
process mid_stripes/position_2.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_3.00/
subscript gradient
process mid_stripes/position_3.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_4.00/
subscript gradient
process mid_stripes/position_4.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_5.00/
subscript gradient
process mid_stripes/position_5.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_6.00/
subscript gradient
process mid_stripes/position_6.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_7.00/
subscript gradient
process mid_stripes/position_7.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_8.00/
subscript gradient
process mid_stripes/position_8.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_9.00/
subscript gradient
process mid_stripes/position_9.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_10.00/
subscript gradient
process mid_stripes/position_10.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_11.00/
subscript gradient
process mid_stripes/position_11.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_12.00/
subscript gradient
process mid_stripes/position_12.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_13.00/
subscript gradient
process mid_stripes/position_13.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_14.00/
subscript gradient
process mid_stripes/position_14.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_15.00/
subscript gradient
process mid_stripes/position_15.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_16.00/
subscript gradient
process mid_stripes/position_16.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_17.00/
subscript gradient
process mid_stripes/position_17.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_18.00/
subscript gradient
process mid_stripes/position_18.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_19.00/
subscript gradient
process mid_stripes/position_19.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_20.00/
subscript gradient
process mid_stripes/position_20.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_21.00/
subscript gradient
process mid_stripes/position_21.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_22.00/
subscript gradient
process mid_stripes/position_22.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_23.00/
subscript gradient
process mid_stripes/position_23.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_24.00/
subscript gradient
process mid_stripes/position_24.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_25.00/
subscript gradient
process mid_stripes/position_25.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_26.00/
subscript gradient
process mid_stripes/position_26.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_27.00/
subscript gradient
process mid_stripes/position_27.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_28.00/
subscript gradient
process mid_stripes/position_28.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_29.00/
subscript gradient
process mid_stripes/position_29.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_30.00/
subscript gradient
process mid_stripes/position_30.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_31.00/
subscript gradient
process mid_stripes/position_31.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_32.00/
subscript gradient
process mid_stripes/position_32.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_33.00/
subscript gradient
process mid_stripes/position_33.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_34.00/
subscript gradient
process mid_stripes/position_34.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_35.00/
subscript gradient
process mid_stripes/position_35.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_36.00/
subscript gradient
process mid_stripes/position_36.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_37.00/
subscript gradient
process mid_stripes/position_37.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_38.00/
subscript gradient
process mid_stripes/position_38.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_39.00/
subscript gradient
process mid_stripes/position_39.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_40.00/
subscript gradient
process mid_stripes/position_40.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_41.00/
subscript gradient
process mid_stripes/position_41.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_42.00/
subscript gradient
process mid_stripes/position_42.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_43.00/
subscript gradient
process mid_stripes/position_43.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_44.00/
subscript gradient
process mid_stripes/position_44.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_45.00/
subscript gradient
process mid_stripes/position_45.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_46.00/
subscript gradient
process mid_stripes/position_46.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_47.00/
subscript gradient
process mid_stripes/position_47.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_48.00/
subscript gradient
process mid_stripes/position_48.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_49.00/
subscript gradient
process mid_stripes/position_49.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_50.00/
subscript gradient
process mid_stripes/position_50.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_51.00/
subscript gradient
process mid_stripes/position_51.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_52.00/
subscript gradient
process mid_stripes/position_52.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_53.00/
subscript gradient
process mid_stripes/position_53.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_54.00/
subscript gradient
process mid_stripes/position_54.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_55.00/
subscript gradient
process mid_stripes/position_55.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_56.00/
subscript gradient
process mid_stripes/position_56.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_57.00/
subscript gradient
process mid_stripes/position_57.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_58.00/
subscript gradient
process mid_stripes/position_58.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_59.00/
subscript gradient
process mid_stripes/position_59.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_60.00/
subscript gradient
process mid_stripes/position_60.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_61.00/
subscript gradient
process mid_stripes/position_61.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_62.00/
subscript gradient
process mid_stripes/position_62.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_63.00/
subscript gradient
process mid_stripes/position_63.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_64.00/
subscript gradient
process mid_stripes/position_64.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_65.00/
subscript gradient
process mid_stripes/position_65.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_66.00/
subscript gradient
process mid_stripes/position_66.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_67.00/
subscript gradient
process mid_stripes/position_67.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_68.00/
subscript gradient
process mid_stripes/position_68.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_69.00/
subscript gradient
process mid_stripes/position_69.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_70.00/
subscript gradient
process mid_stripes/position_70.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_71.00/
subscript gradient
process mid_stripes/position_71.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_72.00/
subscript gradient
process mid_stripes/position_72.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_73.00/
subscript gradient
process mid_stripes/position_73.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_74.00/
subscript gradient
process mid_stripes/position_74.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_75.00/
subscript gradient
process mid_stripes/position_75.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_76.00/
subscript gradient
process mid_stripes/position_76.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_77.00/
subscript gradient
process mid_stripes/position_77.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_78.00/
subscript gradient
process mid_stripes/position_78.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_79.00/
subscript gradient
process mid_stripes/position_79.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_80.00/
subscript gradient
process mid_stripes/position_80.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_81.00/
subscript gradient
process mid_stripes/position_81.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_82.00/
subscript gradient
process mid_stripes/position_82.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_83.00/
subscript gradient
process mid_stripes/position_83.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_84.00/
subscript gradient
process mid_stripes/position_84.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_85.00/
subscript gradient
process mid_stripes/position_85.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_86.00/
subscript gradient
process mid_stripes/position_86.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_87.00/
subscript gradient
process mid_stripes/position_87.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_88.00/
subscript gradient
process mid_stripes/position_88.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_89.00/
subscript gradient
process mid_stripes/position_89.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_90.00/
subscript gradient
process mid_stripes/position_90.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_91.00/
subscript gradient
process mid_stripes/position_91.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_92.00/
subscript gradient
process mid_stripes/position_92.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_93.00/
subscript gradient
process mid_stripes/position_93.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_94.00/
subscript gradient
process mid_stripes/position_94.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_95.00/
subscript gradient
process mid_stripes/position_95.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_96.00/
subscript gradient
process mid_stripes/position_96.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_97.00/
subscript gradient
process mid_stripes/position_97.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_98.00/
subscript gradient
process mid_stripes/position_98.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_99.00/
subscript gradient
process mid_stripes/position_99.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_100.00/
subscript gradient
process mid_stripes/position_100.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_101.00/
subscript gradient
process mid_stripes/position_101.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_102.00/
subscript gradient
process mid_stripes/position_102.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_103.00/
subscript gradient
process mid_stripes/position_103.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_104.00/
subscript gradient
process mid_stripes/position_104.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_105.00/
subscript gradient
process mid_stripes/position_105.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_106.00/
subscript gradient
process mid_stripes/position_106.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_107.00/
subscript gradient
process mid_stripes/position_107.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_108.00/
subscript gradient
process mid_stripes/position_108.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_109.00/
subscript gradient
process mid_stripes/position_109.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_110.00/
subscript gradient
process mid_stripes/position_110.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_111.00/
subscript gradient
process mid_stripes/position_111.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_112.00/
subscript gradient
process mid_stripes/position_112.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_113.00/
subscript gradient
process mid_stripes/position_113.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_114.00/
subscript gradient
process mid_stripes/position_114.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_115.00/
subscript gradient
process mid_stripes/position_115.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_116.00/
subscript gradient
process mid_stripes/position_116.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_117.00/
subscript gradient
process mid_stripes/position_117.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_118.00/
subscript gradient
process mid_stripes/position_118.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_119.00/
subscript gradient
process mid_stripes/position_119.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_120.00/
subscript gradient
process mid_stripes/position_120.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_121.00/
subscript gradient
process mid_stripes/position_121.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_122.00/
subscript gradient
process mid_stripes/position_122.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_123.00/
subscript gradient
process mid_stripes/position_123.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_124.00/
subscript gradient
process mid_stripes/position_124.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_125.00/
subscript gradient
process mid_stripes/position_125.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_126.00/
subscript gradient
process mid_stripes/position_126.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_127.00/
subscript gradient
process mid_stripes/position_127.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_128.00/
subscript gradient
process mid_stripes/position_128.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_129.00/
subscript gradient
process mid_stripes/position_129.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_130.00/
subscript gradient
process mid_stripes/position_130.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_131.00/
subscript gradient
process mid_stripes/position_131.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_132.00/
subscript gradient
process mid_stripes/position_132.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_133.00/
subscript gradient
process mid_stripes/position_133.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_134.00/
subscript gradient
process mid_stripes/position_134.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_135.00/
subscript gradient
process mid_stripes/position_135.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_136.00/
subscript gradient
process mid_stripes/position_136.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_137.00/
subscript gradient
process mid_stripes/position_137.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_138.00/
subscript gradient
process mid_stripes/position_138.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_139.00/
subscript gradient
process mid_stripes/position_139.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_140.00/
subscript gradient
process mid_stripes/position_140.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_141.00/
subscript gradient
process mid_stripes/position_141.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_142.00/
subscript gradient
process mid_stripes/position_142.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_143.00/
subscript gradient
process mid_stripes/position_143.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_144.00/
subscript gradient
process mid_stripes/position_144.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_145.00/
subscript gradient
process mid_stripes/position_145.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_146.00/
subscript gradient
process mid_stripes/position_146.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_147.00/
subscript gradient
process mid_stripes/position_147.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_148.00/
subscript gradient
process mid_stripes/position_148.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_149.00/
subscript gradient
process mid_stripes/position_149.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_150.00/
subscript gradient
process mid_stripes/position_150.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_151.00/
subscript gradient
process mid_stripes/position_151.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_152.00/
subscript gradient
process mid_stripes/position_152.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_153.00/
subscript gradient
process mid_stripes/position_153.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_154.00/
subscript gradient
process mid_stripes/position_154.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_155.00/
subscript gradient
process mid_stripes/position_155.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_156.00/
subscript gradient
process mid_stripes/position_156.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_157.00/
subscript gradient
process mid_stripes/position_157.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_158.00/
subscript gradient
process mid_stripes/position_158.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_159.00/
subscript gradient
process mid_stripes/position_159.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_160.00/
subscript gradient
process mid_stripes/position_160.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_161.00/
subscript gradient
process mid_stripes/position_161.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_162.00/
subscript gradient
process mid_stripes/position_162.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_163.00/
subscript gradient
process mid_stripes/position_163.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_164.00/
subscript gradient
process mid_stripes/position_164.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_165.00/
subscript gradient
process mid_stripes/position_165.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_166.00/
subscript gradient
process mid_stripes/position_166.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_167.00/
subscript gradient
process mid_stripes/position_167.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_168.00/
subscript gradient
process mid_stripes/position_168.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_169.00/
subscript gradient
process mid_stripes/position_169.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_170.00/
subscript gradient
process mid_stripes/position_170.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_171.00/
subscript gradient
process mid_stripes/position_171.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_172.00/
subscript gradient
process mid_stripes/position_172.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_173.00/
subscript gradient
process mid_stripes/position_173.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_174.00/
subscript gradient
process mid_stripes/position_174.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_175.00/
subscript gradient
process mid_stripes/position_175.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_176.00/
subscript gradient
process mid_stripes/position_176.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_177.00/
subscript gradient
process mid_stripes/position_177.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_178.00/
subscript gradient
process mid_stripes/position_178.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_179.00/
subscript gradient
process mid_stripes/position_179.00/
status
move 1.00
delay 2.000
prefix mid_stripes/position_180.00/
subscript gradient
process mid_stripes/position_180.00/
status
