prefix stage_calib_dense/
prefix stage_calib_dense/position_0.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_2.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_4.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_6.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_8.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_10.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_12.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_14.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_16.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_18.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_20.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_22.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_24.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_26.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_28.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_30.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_32.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_34.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_36.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_38.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_40.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_42.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_44.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_46.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_48.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_50.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_52.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_54.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_56.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_58.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_60.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_62.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_64.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_66.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_68.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_70.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_72.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_74.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_76.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_78.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_80.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_82.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_84.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_86.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_88.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_90.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_92.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_94.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_96.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_98.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_100.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_102.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_104.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_106.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_108.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_110.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_112.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_114.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_116.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_118.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_120.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_122.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_124.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_126.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_128.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_130.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_132.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_134.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_136.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_138.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_140.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_142.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_144.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_146.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_148.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense/position_150.00/
subscript checker_center
status
