prefix stage_calib_dense_visible/
prefix stage_calib_dense_visible/position_0/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_2/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_4/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_6/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_8/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_10/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_12/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_14/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_16/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_18/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_20/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_22/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_24/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_26/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_28/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_30/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_32/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_34/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_36/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_38/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_40/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_42/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_44/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_46/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_48/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_50/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_52/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_54/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_56/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_58/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_60/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_62/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_64/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_66/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_68/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_70/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_72/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_74/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_76/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_78/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_80/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_82/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_84/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_86/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_88/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_90/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_92/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_94/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_96/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_98/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_100/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_102/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_104/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_106/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_108/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense_visible/position_110/
subscript checker_center
status
