prefix stage_calib_dense/
prefix stage_calib_dense/position_0/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_2/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_4/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_6/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_8/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_10/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_12/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_14/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_16/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_18/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_20/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_22/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_24/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_26/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_28/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_30/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_32/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_34/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_36/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_38/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_40/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_42/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_44/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_46/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_48/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_50/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_52/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_54/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_56/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_58/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_60/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_62/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_64/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_66/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_68/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_70/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_72/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_74/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_76/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_78/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_80/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_82/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_84/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_86/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_88/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_90/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_92/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_94/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_96/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_98/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_100/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_102/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_104/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_106/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_108/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_110/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_112/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_114/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_116/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_118/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_120/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_122/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_124/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_126/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_128/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_130/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_132/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_134/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_136/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_138/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_140/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_142/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_144/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_146/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_148/
subscript checker_center
status
move 2
delay 2.000000
prefix stage_calib_dense/position_150/
subscript checker_center
status
