prefix stage_calib_dense_visible/
prefix stage_calib_dense_visible/position_0.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_2.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_4.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_6.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_8.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_10.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_12.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_14.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_16.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_18.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_20.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_22.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_24.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_26.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_28.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_30.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_32.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_34.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_36.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_38.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_40.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_42.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_44.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_46.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_48.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_50.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_52.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_54.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_56.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_58.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_60.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_62.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_64.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_66.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_68.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_70.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_72.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_74.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_76.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_78.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_80.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_82.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_84.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_86.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_88.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_90.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_92.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_94.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_96.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_98.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_100.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_102.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_104.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_106.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_108.00/
subscript checker_center
status
move 2.00
delay 2.000
prefix stage_calib_dense_visible/position_110.00/
subscript checker_center
status
