prefix stripes/
prefix stripes/position_0.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_5.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_10.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_15.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_20.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_25.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_30.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_35.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_40.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_45.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_50.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_55.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_60.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_65.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_70.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_75.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_80.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_85.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_90.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_95.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_100.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_105.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_110.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_115.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_120.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_125.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_130.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_135.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_140.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_145.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_150.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_155.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_160.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_165.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_170.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_175.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_180.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_185.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_190.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_195.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_200.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_205.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_210.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_215.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_220.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_225.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_230.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_235.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_240.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_245.00/
subscript gradient
status
move 5.00
delay 2.000
prefix stripes/position_250.00/
subscript gradient
status
