prefix stripes/
prefix stripes/position_0.00/
subscript gradient
process stripes/position_0.00/
status
move 4.00
delay 2.000
prefix stripes/position_4.00/
subscript gradient
process stripes/position_4.00/
status
move 4.00
delay 2.000
prefix stripes/position_8.00/
subscript gradient
process stripes/position_8.00/
status
move 4.00
delay 2.000
prefix stripes/position_12.00/
subscript gradient
process stripes/position_12.00/
status
move 4.00
delay 2.000
prefix stripes/position_16.00/
subscript gradient
process stripes/position_16.00/
status
move 4.00
delay 2.000
prefix stripes/position_20.00/
subscript gradient
process stripes/position_20.00/
status
move 4.00
delay 2.000
prefix stripes/position_24.00/
subscript gradient
process stripes/position_24.00/
status
move 4.00
delay 2.000
prefix stripes/position_28.00/
subscript gradient
process stripes/position_28.00/
status
move 4.00
delay 2.000
prefix stripes/position_32.00/
subscript gradient
process stripes/position_32.00/
status
move 4.00
delay 2.000
prefix stripes/position_36.00/
subscript gradient
process stripes/position_36.00/
status
move 4.00
delay 2.000
prefix stripes/position_40.00/
subscript gradient
process stripes/position_40.00/
status
move 4.00
delay 2.000
prefix stripes/position_44.00/
subscript gradient
process stripes/position_44.00/
status
move 4.00
delay 2.000
prefix stripes/position_48.00/
subscript gradient
process stripes/position_48.00/
status
move 4.00
delay 2.000
prefix stripes/position_52.00/
subscript gradient
process stripes/position_52.00/
status
move 4.00
delay 2.000
prefix stripes/position_56.00/
subscript gradient
process stripes/position_56.00/
status
move 4.00
delay 2.000
prefix stripes/position_60.00/
subscript gradient
process stripes/position_60.00/
status
move 4.00
delay 2.000
prefix stripes/position_64.00/
subscript gradient
process stripes/position_64.00/
status
move 4.00
delay 2.000
prefix stripes/position_68.00/
subscript gradient
process stripes/position_68.00/
status
move 4.00
delay 2.000
prefix stripes/position_72.00/
subscript gradient
process stripes/position_72.00/
status
move 4.00
delay 2.000
prefix stripes/position_76.00/
subscript gradient
process stripes/position_76.00/
status
move 4.00
delay 2.000
prefix stripes/position_80.00/
subscript gradient
process stripes/position_80.00/
status
move 4.00
delay 2.000
prefix stripes/position_84.00/
subscript gradient
process stripes/position_84.00/
status
move 4.00
delay 2.000
prefix stripes/position_88.00/
subscript gradient
process stripes/position_88.00/
status
move 4.00
delay 2.000
prefix stripes/position_92.00/
subscript gradient
process stripes/position_92.00/
status
move 4.00
delay 2.000
prefix stripes/position_96.00/
subscript gradient
process stripes/position_96.00/
status
move 4.00
delay 2.000
prefix stripes/position_100.00/
subscript gradient
process stripes/position_100.00/
status
move 4.00
delay 2.000
prefix stripes/position_104.00/
subscript gradient
process stripes/position_104.00/
status
move 4.00
delay 2.000
prefix stripes/position_108.00/
subscript gradient
process stripes/position_108.00/
status
move 4.00
delay 2.000
prefix stripes/position_112.00/
subscript gradient
process stripes/position_112.00/
status
move 4.00
delay 2.000
prefix stripes/position_116.00/
subscript gradient
process stripes/position_116.00/
status
move 4.00
delay 2.000
prefix stripes/position_120.00/
subscript gradient
process stripes/position_120.00/
status
move 4.00
delay 2.000
prefix stripes/position_124.00/
subscript gradient
process stripes/position_124.00/
status
move 4.00
delay 2.000
prefix stripes/position_128.00/
subscript gradient
process stripes/position_128.00/
status
move 4.00
delay 2.000
prefix stripes/position_132.00/
subscript gradient
process stripes/position_132.00/
status
move 4.00
delay 2.000
prefix stripes/position_136.00/
subscript gradient
process stripes/position_136.00/
status
move 4.00
delay 2.000
prefix stripes/position_140.00/
subscript gradient
process stripes/position_140.00/
status
move 4.00
delay 2.000
prefix stripes/position_144.00/
subscript gradient
process stripes/position_144.00/
status
move 4.00
delay 2.000
prefix stripes/position_148.00/
subscript gradient
process stripes/position_148.00/
status
move 4.00
delay 2.000
prefix stripes/position_152.00/
subscript gradient
process stripes/position_152.00/
status
move 4.00
delay 2.000
prefix stripes/position_156.00/
subscript gradient
process stripes/position_156.00/
status
move 4.00
delay 2.000
prefix stripes/position_160.00/
subscript gradient
process stripes/position_160.00/
status
move 4.00
delay 2.000
prefix stripes/position_164.00/
subscript gradient
process stripes/position_164.00/
status
move 4.00
delay 2.000
prefix stripes/position_168.00/
subscript gradient
process stripes/position_168.00/
status
move 4.00
delay 2.000
prefix stripes/position_172.00/
subscript gradient
process stripes/position_172.00/
status
move 4.00
delay 2.000
prefix stripes/position_176.00/
subscript gradient
process stripes/position_176.00/
status
move 4.00
delay 2.000
prefix stripes/position_180.00/
subscript gradient
process stripes/position_180.00/
status
